- assets/misc/registries.yaml
- zarf.yaml
Add file /etc/rancher/k3s/registries.yaml to init package which will tell k3s to automatically use `zarf.localhost` as a registry mirror for various remote registries
> Add repo mirroring

- examples/Makefile
Fixing a couple of minor issues after integrating the changes from the big bang demo which changed the structure of the VM and mounted folder from `.../build` to `.../sync`
> Fix makefile for postgres-operator example

- assets/manifests/utility/gitea.yaml
- assets/manifests/utility/registry.yaml
- Add resource requests and limits to Gitea and the private docker registry because not having them is a finding in `kubescape` and other k8s security tools
> Add resource requests and limits to Utility Cluster deployments

- cli/cmd/prepare.go
- cli/internal/packager/create.go
- cli/internal/packager/deploy.go
- cli/internal/utils/shasum.go
- e2e.sh
Finally closes #11.  This PR adds a new `zarf prepare sha256sum` command for internally generating hashes.  On package create/deploy the operation will fail if a SHASUM is specified but does not match the computed result.  Added a single E2E for the prepare command, the other code is already covered by other E2E tests.
> Implement SHA256SUM validation

- examples/Vagrantfile
- examples/big-bang/README.md
- examples/big-bang/template/bigbang/kustomization.yaml
- examples/big-bang/template/bigbang/values.yaml
- examples/big-bang/template/flux/kustomization.yaml
- examples/big-bang/zarf.yaml
- Update Big Bang example to BB v1.17.0
- Misc adjustments
- Change port forwarding in Vagrantfile to directly forward the 2 new ports rather than expose different ports on the host than are exposed on the guest. From the user's perspective this makes no difference whatsoever but it feels cleaner to me
- Update examples/big-bang/README.md: Add a table with all the service endpoints, usernames, and passwords, and add a note about needing to delete the `EnvoyFilter` from [this bug](https://repo1.dso.mil/platform-one/big-bang/bigbang/-/issues/802)
- Update the NetworkPolicies with real a real CIDR
- Update to the new `bigbang.dev` cert
- Tweak resources for a better fit on a developer laptop
- Reorder the YAML blocks in examples/big-bang/template/bigbang/values.yaml so they are in the same …
> Upgrade Big Bang Core example to BB v1.17.0

- cli/cmd/package.go
- cli/config/config.go
- cli/internal/packager/deploy.go
- test/e2e/e2e_general_cli_test.go
Adding the ability for Zarf to deploy remote packages. This checks if the deployPath given is a URL with a file extension we recognize. If the path is a valid package it gets downloaded to /temp and processed.
This also renames `packageName` to `packagePath` to try to show that the variable is more than just a name and could either be a full path to a file or even a URL to some online resource.
**Potential Issues To Add After Merge:**
> Add ability to deploy remote packages

- .gitlab-ci.yml
Fix the GitLab release pipeline by utilizing different secrets (the new Zarf robot account we just got)
I have NOT added these secrets yet to the Zarf repo in Repo1. I will do so after this gets approved but before it gets merged.
> Fix the GitLab release pipeline

- .gitlab-ci.yml
- e2e.sh
* Remove a test for the docker registry from the legacy E2E tests, since that functionality already gets tested in GitHub actions
* Remove the legacy E2E tests from the critical path to cutting a release. This is safe as long as "Require branches to be up to date before merging" is turned on and we trust the GitHub Actions pipeline to be definitive.
> Fix the legacy E2E tests and remove them from the critical path to cutting a release

- docs/ironbank.md
Removes a single, extraneous word from the Iron Bank login instructions.
> docs: fix typo

- cli/Makefile
I noticed when testing things today that my `zarf version` was still returning 0.12 even though 0.13 was released and I had the latest changes in master. Turns out 'git describe' only returns the latest annotated tag. When building binaries we want to catch all tags, not just annotated ones.
`git describe --tags` returns the latest tag, annotated or not.
> Update build to catch all tags, not just annotated ones

- cli/internal/git/checkout.go
- cli/internal/git/fetch.go
- cli/internal/git/pull.go
- cli/internal/git/push.go
- cli/internal/git/utils.go
- cli/internal/packager/create.go
- examples/gitops-data/README.md
- examples/gitops-data/zarf.yaml
Update the pull function so that tag-provided mirrors do not fetch all
tags, instead later fetching (externally) only the tag they need.
Implement tag fetching function to retrieve _only_ the desired tag when
creating a tag-provided repo mirror.
Checkout the tag into a detatched HEAD state at the end of the create
stage of tag-provided repository mirrors.
Implement ref removal and addition functions used during package
creation and mirror push to ensure that refs that aren't wanted on the
mirror won't be pushed.
Update the refspecs used in the push to push detatched HEAD, branches,
online remote, and tags to the offline mirror. Note that if we later
checkout a branch from the remote and do not clean up the remote ref it
will lead to a duplicate ref name and the push will fail on one of …
> Git Repository Overhaul

- test/tf/public-ec2-instance/main.tf
We are currently using the latest docker image of CloudPosse which updated the version of Terraform which was breaking our e2e tests.
This is a major update of terraform though so hopefully nothing breaks.. Lets find out..
> Change terraform version

- cli/cmd/initialize.go
When using the host suggestion list, IPv6 address break the init due to an invalid hostname format.  This is something we 
can look at further down the road but I don't think we're ready to sign up for full IPv6 support today for a number of reasons.
> filter init host suggestions by hostname validator

- cli/internal/packager/create.go
Without this, the regex will not catch charts provided by git and all charts downloaded as a published chart.
I was trying to build the postgres example package and was getting an error because it was trying to download helm charts as a published helm chart instead of as a chart hosted on a git repo.
> Bug Fix: Fix regexp creation to use a proper string

- cli/internal/git/checkout.go
- cli/internal/git/utils.go
> Fix error handling when building a zarf package with gitops repos that have `@tag` format

- .github/workflows/test-command.yml
- Makefile
- test/e2e/e2e_gitea_and_grafana_test.go
This PR will add the baseline for a new test, a new PR will add the actual test. It has to be done this way because GitHub Actions only pulls its job definitions from master, not branches.
> Add skeleton of new E2E test that tests Gitea and Grafana

- examples/postgres-operator/README.md
- examples/postgres-operator/manifests/image-pull-secret.yaml
- examples/postgres-operator/manifests/postgres-cluster.yaml
- examples/postgres-operator/manifests/postgres-operator.yaml
- examples/postgres-operator/zarf.yaml
Should fix #201 It appears the postgres-cluster yaml was not present in the newer versions of this example and thus the database pods were not being created accordingly.
> reintroduce postgres operator example database pods

- Makefile
Master currently fails the e2e because the gitops package isn't being created to the run e2e tests against.
> Add gitops data package creation prior to e2e test

- cli/internal/helm/post-render.go
We experienced a race condition when updating the ServiceAccount for a newly created namespace.
Sometimes KIND distro would  error because it was still updating the SA at the same time we were.
Without this change we were sometimes seeing the following error on KIND clusters:
` DEBUG   unable to update the default service account for the demo namespace: Operation cannot be fulfilled on serviceaccounts "default": the object has been modified; please apply your changes to the latest version and try again`
I've tested this several times (more than 5..) locally (macOS and Linux) and have not run into the ImagePullBackoff because of an un-updated ServiceAccount.
> update post-render to retry updating service account on error

- assets/scripts/k3s.service
- assets/scripts/zarf-clean-k3s.sh
- cli/cmd/destroy.go
- examples/big-bang/README.md
- examples/big-bang/zarf.yaml
- test/e2e/e2e_data_injection_test.go
- zarf.yaml
> 296: Using /usr/sbin instead of /usr/local/bin to accommodate RHEL

- Makefile
- cli/internal/packager/common.go
- test/e2e/e2e_general_cli_test.go
* This is so we can read the config.confirm value later to determine if the command is being run in 'script' mode.
This gives us the ability to be confident if/when we can prompt the user with a question.
> 200 confirm prompting components

- Makefile
- examples/gitops-data/zarf.yaml
- test/e2e/e2e_gitops_example_test.go
- Make GitOps E2E test more robust by using a newer tag that got created after the major force push to master
- Minor cleanup of dead code
> Make GitOps E2E test more robust + minor cleanup

- cli/internal/message/message.go
Depending on what functions are called for debug/trace the wrong callstack offsets could occur creating a problem where the wrong debug point is listed (sometimes within a library making it difficult to understand the issue)
> Normalize trace references for debug/trace output

- cli/internal/k8s/common.go
- test/e2e/e2e_general_cli_test.go
This PR adds a check for the $KUBECONFIG environment variable when Zarf is trying to generate a config to talk to a native kubernetes cluster.
Closes #315
> Check for a $KUBECONFIG env-variable

- cli/cmd/destroy.go
- cli/internal/helm/post-render.go
- cli/internal/k8s/namespace.go
Checking that a secret exists isn't enough, we want to make sure the contents of the secret are what we expect it to be.
Fixes #330
> Update post-renderer to verify secret data for existing secrets

- .adr-dir
- .tool-versions
- CONTRIBUTING.md
- docs/adr/0001-record-architecture-decisions.md
- docs/adr/template.md
* Add docs on our choice to use ADRs and how to use the `adr-tools` CLI
* Minor updates to the Contributor guide based on changes we've made to our GitHub setup
> Update Contributor Guide & Add ADR docs

- cli/internal/k8s/common.go
- cli/internal/packager/seed.go
- zarf.yaml
The previous command was just running the 'k get nodes' command without verifying any nodes were actually returned.
As part of the 'after' script definitions for the k3s component we will now verify that at least 1 k3s node is returned when 'kubectl get nodes' is executed.
> k3s component actually waits for node to come up

- assets/scripts/zarf-clean-k3s.sh
- cli/cmd/destroy.go
- cli/config/config.go
- zarf.yaml
If zarf init was not able to successfully start up a k3s cluster then no state-secret will exist in the cluster for Zarf to determine if k3s was installed when 'zarf init' was run. In these cases we should search for the scripts to remove k3s on the local file system and try to execute them.
Fixes #371
> Give warning message if invalid permissions to destroy empty local k3s cluster

- .github/workflows/enforce-labels.yml
Add a workflow that checks if certain 'banned' labels have been applied to a PR. If the labels exist, the workflow will fail preventing a merge. This is useful as we review PRs so we can make sure proper documentation and tests have been added before getting merged.
Closes #352
> Add workflow to disable PR if certain labels exist

- test/e2e/e2e_composability_test.go
Now using require.NoError in test parts which are critical
Fixes #405
> Replace assert with require in critical parts

- cli/internal/k8s/common.go
Supports KUBECONFIG env vars in a way that more closely resembles how `kubectl` handles it, by utilizing the defaults in the `client-go` library
Related to #373 (but doesn't close it since it isn't adding a needed E2E test)
> Better KUBECONFIG support

- .github/workflows/test-k3d.yml
- .github/workflows/test-k3s.yml
- .github/workflows/test-kind.yml
- .golangci.yml
- Makefile
- cli/internal/k8s/common.go
- test/e2e/README.md
- test/e2e/clusters/clusters.go
- test/e2e/common.go
- test/e2e/e2e_composability_test.go
- test/e2e/e2e_example_game_test.go
- test/e2e/e2e_gitea_and_grafana_test.go
- test/e2e/e2e_gitops_example_test.go
- test/e2e/main_test.go
Simplifies the handling of kubernetes clusters from this logic:
1. Determine if a cluster is already running, and if it is, use it instead of creating one
1. If a cluster isn't running, create one using the Golang libraries for Kind and/or K3d, using a hard-coded `KUBECONFIG` file (`~/.kube/config`)
- If TESTDISTRO is not set, run the tests twice, once on KinD, and again on K3d
- If TESTDISTRO is set to either `kind` or `k3d` only do that one
1. Run the tests
1. Destroy the cluster if it was created and delete the `~/.kube/config` file 
To this:
1. Expect TESTDISTRO env var to be set, with value one of `provided`, `kind`, `k3d`, or `k3s` and error out if it isn't
1. If TESTDISTRO is 
- `kind` or `k3d` -- create that cluster using the associated golang library, using a temporary file for …
> Simplify cluster instantiation in tests

- .github/workflows/release.yml
Difficult to test master workflows in PRs--this tiny PR addresses issues found after merge, fix for #370 after #408.  Relevant docs:  https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs.
> Fix workflow yaml for github release 

- cli/internal/git/utils.go
…
Even though the credentialParser is capturing an error during the parsing, it tries to retrieve the password without being sure the error is nil
Fixes # (issue)
#418
> fix(credentialParser): validate error before parsing password to avoid nil pointer. #418

- docs/components.md
- docs/what-is-zarf.md
- examples/big-bang/README.md
- examples/istio-with-separate-cert/README.md
- packages/gitea/zarf.yaml
- src/test/e2e/e2e_gitea_and_grafana_test.go
- src/test/e2e/e2e_gitops_example_test.go
- zarf.yaml
Update the name of the `gitops-service` component in the init config to `git-server`, since it now only includes a git server. 
none
> Update gitops-service component in init config

- examples/big-bang/kustomization/values.yaml
Update the TLS cert in the Big Bang example (it was expired)
none
> Update TLS cert in Big Bang example

- Makefile
- examples/component-scripts/zarf.yaml
- packages/distros/eks/eks.yaml
- packages/distros/eks/zarf.yaml
- src/cmd/destroy.go
- src/cmd/tools.go
- src/internal/packager/common.go
- src/internal/packager/deploy.go
- src/internal/packager/validate/validate.go
- src/internal/pki/pki.go
- src/internal/utils/exec.go
- src/test/e2e/e2e_component_scripts_test.go
- src/test/e2e/e2e_general_cli_test.go
- src/types/types.go
- zarf.schema.json
Add the ability to define a script timeout length in seconds and show logs inline.  Also added an EKS example use-case for when this would be useful
Example:
```
- name: example-one-hour-timeout-with-show-logs
scripts:
timeout: 3600
showOutput: true
before:
- "some-long-running-command-here"
```
Fixes #338
> 338 configurable script timeout

- examples/README.md
Add nav links to the `./examples/README.md` so that people who click the `examples` tab on the zarf.dev website can actually see more information about the different examples we have created.
Closes #468
> add nav links to main example README

- examples/gitops-data/zarf.yaml
- src/internal/git/pull.go
- src/internal/git/push.go
This PR allows for graceful failure on various go-git cloning issues related to authentication, git protocol, etc during the `zarf package create` execution.  On a clone failure, the git package will attempt to call the host-based `git clone` before completely failing.  Note that due to the format of Azure http git clone urls, this command will not support single-tag/single-depth clones in this PR.  
Related to #456 
Fixes #417
> Fallback to host-provided git on clone failure during package create

- packages/zarf-registry/registry-values.yaml
- packages/zarf-registry/zarf.yaml
> Resolve env variable secrets in the docker registry helm chart

- src/config/config.go
- src/internal/images/push.go
> Use registry secrets

- Makefile
- examples/helm-with-different-releaseName-values/values.yaml
- examples/helm-with-different-releaseName-values/zarf.yaml
- src/internal/helm/chart.go
- src/test/e2e/e2e_helm_test.go
- src/types/types.go
- zarf.schema.json
Added `releaseName` property to ZarfChart and updated the install/upgrade chart function to use `releaseName` if provided or fall back to `name` if not provided to keep backwards compatibility and not require the new property.
Tested this change by deploying multiple copies of cert-manager chart (just as a test) to the same namespace using different Zarf components and the same Zarf component with a list of charts too.
```
kind: ZarfPackageConfig
metadata:
name: test-helm-releasename
description: "Deploys same chart with different names"
components:
- name: cert-manager
required: false
charts:
- name: cert-manager
url: https://charts.jetstack.io
version: 1.6.3
namespace: cert-manager
images:
- "quay.io/jetstack/cert-manager-cainjector:v1.6.3"
- …
```
> Add helm release name property to zarf chart

- src/cmd/package.go
- src/cmd/tools.go
- src/config/config.go
- src/internal/images/copy.go
- src/internal/images/pull.go
- src/internal/images/push.go
- src/internal/packager/injector.go
- src/internal/packager/prepare.go
- src/internal/sbom/catalog.go
- src/types/types.go
Adds a `--insecure` flag to `zarf package create` to allow creating packages from insecure registries.
Fixes #497
> Add insecure flag to zarf package create

- .github/workflows/release.yml
- .gitignore
- .goreleaser.yaml
- README.md
- src/cmd/initialize.go
- src/internal/utils/io.go
Uses GoReleaser to build, release, and publish the tagged releases pushed to the repo.
Through this pipeline update, GoReleaser will publish a brew recipe to the [Defense Unicorns Tap](https://github.com/defenseunicorns/homebrew-tap) for the tagged release.
> Use GoReleaser for GitHub release workflow

- .golangci.yml
Super small QoL improvement to update our pre-commit hook to only report issues for new changes that are being introduced.
I'll be honest, since the pre-commit linter was always checking and reporting against the entire codebase I would **always** commit any Go changes with the `--no-verify` flag, I probably contributed a lot of small linting no-no's because of that.
Because of the nature of `golangci-lint` this will still **run** against the entire project (so it might take a couple seconds to run until we cleanup the repo more) but this change should hopefully get us working towards that better direction.
> update linter to only report new issues

- src/cmd/agent.go
- src/cmd/connect.go
- src/cmd/destroy.go
- src/cmd/initialize.go
- src/cmd/package.go
- src/cmd/prepare.go
- src/cmd/tools.go
- src/cmd/version.go
Improve the CLI `--help` message outputs.
> Better CLI Help Messages

- .github/workflows/release.yml
- src/cmd/initialize.go
- src/config/config.go
- src/internal/utils/github.go
Enhanced the quick start process for testing Zarf by prompting users to download the init package if it can't be found locally. 
Closes #502
> Add init package downloader

- .goreleaser.yaml
Apparently goreleaser thought it would be swell to strip the (perfectly legal) v prefix from the version tag....
https://goreleaser.com/customization/templates/#fn:1
> Fix goreleaser version

- packages/big-bang-core/kustomization/core-light/kustomization.yaml
A small typo was introduced with the big bang core example -> packages move in #488, this corrects that.  Since we do not have the ability to run this in E2E right now due to IB credentials and how SUPER long it would take to fully test, including screenshots in the PR after testing from M1 -> Ubuntu AMD64 remote machine using https://github.com/alexellis/k3sup.
> fix kustomize path for big-bang core package

- src/internal/k8s/images.go
- src/internal/packager/injector.go
- Switch to default image pull policy to simplify connected-cloud deployments
- Add more code comments to clarify podspec in the code
- Add node affinity for more reliable image mounting with multi-node clusters
- Extend the configmap push interval 100ms -> 250ms to reduce mount failures/control plane pressure (cost is slightly slower configmap apply)
#501
> Injector stability improvements

- packages/distros/k3s/zarf.yaml
Upgrades the version of K3s used in the init package from v1.23.6+k3s1 to v1.24.1+k3s1
Fixes #538
> Upgrade K3s package to v1.24.1+k3s1

- packages/distros/eks/zarf.yaml
We determine the system architecture through 'uname -m' which outputs x86_64 for Mac's w/ intel chips.
This changes the target location name to match that output so the script can find/use it later.
> Update target location for ekcstl for Darwin amd64 builds

- examples/README.md
The BigBang link in the examples README was leading to a 404 on github. This is a problem since the first example when going to the examples on https://zarf.dev is the bigbang link. 
#546
> 546. Fixed broken bigbang link in examples README.

- .hooks/verify-zarf-schema.sh
- Makefile
- main.go
- src/cmd/package.go
- src/config/config.go
- src/internal/packager/common.go
- src/main.go
- src/test/e2e/e2e_remote_sget_test.go
- src/types/types.go
Provides support for specifying a remote signed package (via cosign/sget) to deploy.  Initial use will be for https://zarf.dev/install/
> Add support for package deploy via cosign sget 

- src/cmd/destroy.go
- src/internal/k8s/namespace.go
- src/internal/k8s/zarf.go
Properly purge secrets with the `app.kubernetes.io/managed-by=zarf` label from all namespaces, regardless of `--remove-components` flag.  These secrets will have no meaning once destroy is run and are not picked up by `--remove-components` currently because they are created out-of-band from helm during the `postRender` stage of the helm install to avoid collisions. 
Fixes #520
> Fully remove zarf secrets from all namespaces

- packages/zarf-agent/manifests/webhook.yaml
Make the Zarf Agent mutate objects on update as well as create
Fixes #564
> Make the agent mutate on update as well as create

- .goreleaser.yaml
Hotfix update goreleaser path to use root directory after #550
> Update goreleaser build path

- src/internal/packager/deploy.go
Referenced `config.ZarfRegistryPushUser` instead of the hardcoded `zarf-push-user` which was incorrectly being displayed in the credentials output after a `zarf init`.
Fixes #577
> Fix registry user in credentials output

- src/internal/git/utils.go
Gitea updated their api and now the `login_name` key is required for PATCH requests.
> update gitea PATCH request to include 'login_name' key

- .github/workflows/zarf-schema-check.yml
- .hooks/jsfh-config.json
- .hooks/verify-zarf-schema.sh
- .hooks/zarf-jsfh-template/base.md
- .hooks/zarf-jsfh-template/breadcrumbs.md
- .hooks/zarf-jsfh-template/content.md
- .hooks/zarf-jsfh-template/section_array.md
- .hooks/zarf-jsfh-template/section_conditional_subschema.md
- .hooks/zarf-jsfh-template/section_description.md
- .hooks/zarf-jsfh-template/section_examples.md
- .hooks/zarf-jsfh-template/section_not.md
- .hooks/zarf-jsfh-template/section_one_of.md
- .hooks/zarf-jsfh-template/section_properties_details.md
- .hooks/zarf-jsfh-template/section_undocumented_required_properties.md
- .hooks/zarf-jsfh-template/tabbed_section.md
- docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
- docs/4-user-guide/2-zarf-packages/2-zarf-components.md
- docs/4-user-guide/3-zarf-schema.md
Generated markdown from zarf.schema.json to include in docs.
Fixes #606
> 606 generate docs from zarf schema json

- docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
While going through the docs on the website I found a link to google.com, fixing it here in the docs
> fixes link in docs

- src/cmd/root.go
This re-adds some behavior to tell users the `zarf zarf-package-thing-arch.tar.zst` is no longer valid.
> Gracefully handle zarf shorthand removal

- src/cmd/initialize.go
- src/cmd/package.go
- src/cmd/prepare.go
- src/internal/packager/common.go
- src/internal/packager/components.go
This adds error checks around the surveys that ask for things other than confirm
Fixes #664
> Add error checking to surveys

- src/internal/packager/create.go
Hotfix PR #670, when counting manifests, also include the # of kustomizations.
> Include kustomizations in manifest count

- examples/README.md
This addresses some feedback from @Madeline-UX on the examples page in coordination with https://github.com/defenseunicorns/zarf-docs/pull/47
None
> Resolve madeline feedback on examples main page

- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_connect.md
- src/cmd/connect.go
Makes the connect command respect linux (and cobra) conventions
Fixes # N/A
> Fix the connect command usage info

- src/cmd/tools.go
- src/internal/images/pull.go
This adds a more descriptive error and fixes issues with the cache clear command
Fixes #813
> Make the corruption error more clear and fix zarf tools cache-clear

- Makefile
Update the agent_image so that we use an agent that calculates checksums of the images instead of shasums in local dev mode.
> Update the AGENT_IMAGE URL in the Makefile

- src/internal/api/packages/deploy.go
- src/types/api.go
- src/ui/lib/api-types.ts
- src/ui/lib/api.ts
- src/ui/routes/initialize/deploy/+page.svelte
There is currently a disconnect between the UI and the CLI experience when `zarf init`ing.  This is because the flow of `zarf init` does not strictly follow the same flow that `zarf package deploy` does.  `ZarfDeployOptions != ZarfInitOptions`.
This PR patches the overall API request flow, but does not add the missing options from `ZarfInitOptions` to the UI. Further discussion is needed in that area.
Fixes #882
> fix init pkg deploy via ui

- src/internal/utils/network.go
Prevent file download failure when the target directory does not exist
Fixes #901
> Ensure a target directory exists prior to downloading files

- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools.md
- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_archiver.md
- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_archiver_compress.md
- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_archiver_decompress.md
- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_gen-pki.md
- src/cmd/tools.go
- src/internal/pki/pki.go
- src/test/e2e/00_use_cli_test.go
This adds a new tools command to generate a PKI chain of trust.
Fixes #915
> Add a generate PKI command

- package-lock.json
- package.json
- src/ui/lib/components/package-component-accordion.svelte
- src/ui/lib/components/package-details-card.svelte
- src/ui/routes/packages/+page.svelte
Update Props in references to UI components specifically change from className and wrapperClass to instead use class. Update imports and removed unused import.
#986
> #986. Bump unicorn-ui to v0.0.21. 

- docs/2-core-concepts.md
Fixes a missing space on the header (reference current docs page - https://docs.zarf.dev/docs/core-concepts ).
> Fix typo on header for core concepts doc

- examples/postgres-operator/README.md
> remove typo character in example command within the postgres readme

- src/cmd/initialize.go
Carry over from #1027 , w/ updates from MZAL.  Did not feel like fixing merge conflicts.
Fixes #985 
Handles creation of `~/.zarf-cache` during `zarf init` if it does not exist.
> create cache dir during zarf init if it does not exist

- src/test/e2e/30_config_file_test.go
Removes a test that was previously needed to make sure a package in a default path was read. Now that #1039 is merged, we have this covered on init package create / deploy + it was was trampling over that file during this test.
> Remove test now covered by zarf init usage of config file

- src/internal/cluster/tunnel.go
- src/internal/packager/git/clone.go
- src/internal/packager/git/pull.go
- src/internal/packager/git/push.go
- src/internal/packager/helm/chart.go
- src/pkg/message/spinner.go
- src/pkg/utils/sget.go
This is a hotfix to remove spinner.Debugf messages from Zarf.  This was a little used feature, but it would often result in missing logs for the places that did use it and had a conflicting purpose already with message.Debugf.
Fixes #N/A
> Remove all spinner.Debugf messages

- .goreleaser.yaml
Brew does not understand how to install `zarf@v0.22.2.rb` but does understand how to install `zarf@0.22.2.rb`
> Publish versioned homebrew releases without a 'v' in the VersionName

- src/pkg/packager/prepare.go
- src/test/e2e/00_use_cli_test.go
Fixes an issue where Zarf could not look at images from local paths.
Fixes #1087
> 1087 prepare find images doesnt work on local helm chart paths

- src/internal/packager/git/fetch.go
- src/internal/packager/git/pull.go
- src/test/e2e/04_create_templating_test.go
- src/test/e2e/05_create_cache_test.go
Fixes a bug introduced from MZAL where cache could be messed with do to GitPath being changed in the git receiver.
Fixes #1079
> Fix where we are deleting tags (don't edit cache\!)

- docs/4-user-guide/4-vscode.md
The zarf.schema.json URL is incorrect on this page; it is now found in raw.githubsercontent.com
> Update zarf.schema.json location URL

- src/internal/packager/sbom/viewer/viewer.js
Adds an undefined check for metadata to viewer.js
Fixes #1131
> Hotfix for metadata potentially being undefined in the SBOM json

- packages/gitea/gitea-values.yaml
- packages/gitea/zarf.yaml
This PR exposes variables for the Git Server in the init package to match the Zarf Registry:
- GIT_SERVER_EXISTING_PVC
- GIT_SERVER_PVC_SIZE
- GIT_SERVER_CPU_REQ
- GIT_SERVER_MEM_REQ
- GIT_SERVER_CPU_LIMIT
- GIT_SERVER_MEM_LIMIT
Fixes #1122 
Related to #1123
> Variabalize Git Server configs

- src/ui/lib/components/index.ts
- src/ui/routes/+layout.svelte
- src/ui/routes/+page.svelte
- src/ui/routes/auth/+page.svelte
- src/ui/routes/initialize/configure/+page.svelte
- src/ui/routes/initialize/finished/+page.svelte
- src/ui/routes/initialize/review/+page.svelte
- src/ui/routes/packages/+page.svelte
Cleans up Svelte imports of internal (from `$lib/components`). I find this to be easier to read, and can take up fewer space.
> Cleanup UI imports

- docs/13-walkthroughs/0-using-zarf-package-create.md
- docs/13-walkthroughs/2-deploying-doom.md
- docs/3-getting-started.md
- docs/4-user-guide/index.md
Correcting minor issues with the docs as I go through them.
> Documentation spelling and grammar fixes.

- src/cmd/tools.go
This issue makes show all namespace the default for the K9 dash. It was made based on user insights and a few user errors that led to users believing their pods were note deployed due to not using the zarf namespace. 
This may also be important for packages that use the big-bang namespace or that deploy other resources that use a namespace other than Zarf
Fixes #1195 1195 (issue)
> Made show all namespace default for k9 dash

- docs/4-user-guide/1-the-zarf-cli/2-cli-commond-uses.md
- docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
Cleaned up the spelling and grammar. Simplified the language. Added clarification that Zarf will only try to install k3s on Linux machines. Added references and links to information that may be unknown or unclear to the reader.
> Update cli docs

- src/cmd/initialize.go
- src/config/lang/english.go
- src/pkg/packager/components.go
- src/types/runtime.go
- src/ui/lib/api-types.ts
This consolidates the components flag (following the pattern from set) so that you can Zarf Package Deploy and init package again.
Fixes #1182
> Consolidate components flag

- src/internal/agent/hooks/flux.go
- src/internal/packager/git/push.go
- src/internal/packager/git/url.go
This removes the requirement for a git url to end in .git
Fixes #482
> Use TransformURL over MutateGitURLsInText for the agent

- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_registry_catalog.md
- src/cmd/tools.go
- src/test/e2e/21_connect_test.go
This wraps the crane command so that it is easier to use more directly with Zarf
Fixes #1186
> Wrap the crane command to make it easier to use with Zarf

- src/internal/packager/sbom/catalog.go
- src/test/e2e/06_create_sbom_test.go
this fixes compare tool generation for things that either don't have images or don't have component sboms.
Fixes #N/A
> fix compare tool generation and add better testing

- src/cmd/initialize.go
- src/cmd/package.go
- src/cmd/prepare.go
- src/pkg/packager/variables.go
- src/pkg/utils/misc.go
Fixes an issue where keys were not being properly merged from --set and viper
Fixes #N/A
> Make viper keys uppercase

- .markdownlintignore
- README.md
- docs-website/README.md
- netlify.toml
> Netlify deploy

- src/pkg/packager/common.go
- src/test/e2e/20_zarf_init_test.go
Fixes an issue where we were not notifying the user of sboms on deploy.
Fixes #1354
> Fix SBOM messaging on deploy

- src/internal/packager/images/pull.go
- src/pkg/message/progress.go
- src/pkg/utils/network.go
Small fix to normalize function signatures in message/progress.go and fix a visual error with progressbar downloads.
Fixes #1375
> Rename and change progressbar signatures to fix visual errors

- docs/1-understand-the-basics.md
Stumbled across some broken links in [this doc](https://github.com/defenseunicorns/zarf/blob/main/docs/1-understand-the-basics.md).  Dug through the [commit history](https://github.com/defenseunicorns/zarf/pull/1276/files#diff-53706aae2f95773ebd248f8d0d160403083ffc18ba649f08ebb35e806c5cd797) and pulled out the correct links.  Tossed the `documentation` label on the PR, not sure but hope that prevents any pipelines from kicking off.  I didn't see anything in the contributor's guide to tackle a doc update.  Please advise if this PR is suitable.
FYI @bdfinst 
Fixes #
> Docs: fixed broken links 

- src/cmd/tools/archiver.go
Upon a successful unarchive, delete the `tar.zst` that is no longer needed when using `zarf tools archiver decompress <package> <dest> --decompress-all`. 
...
Before behavior:
```
ocipkg/
├── components
│   ├── keyval
│   │   └── manifests
│   │       └── k3s
│   │           ├── hornstash-deploy.yaml
│   │           └── zarf-service.yaml
│   └── keyval.tar.zst
├── images.tar
├── sboms
│   ├── compare.html
│   ├── registry.gitlab.com_buzzdeploy_apps_horn-stash_main-amd64.json
│   └── sbom-viewer-registry.gitlab.com_buzzdeploy_apps_horn-stash_main-amd64.html
├── zarf-1135963779
└── zarf.yaml
```
After:
```
ocipkg/
├── components
│   └── keyval
│       └── manifests
│           └── k3s
│               ├── hornstash-deploy.yaml
│               └── zarf-service.yaml
├── images.tar
├── sboms …
```
> deletes tar.zst of components after unarchive

- CODEOWNERS
This adds @wirewc to the CODEOWNERS file
Fixes #N/A
> Add wirewc to CODEOWNERS

- examples/component-actions/.gitignore
- src/internal/packager/images/common.go
- src/internal/packager/images/pull.go
- src/internal/packager/images/push.go
- src/internal/packager/sbom/catalog.go
- src/internal/packager/sbom/tools.go
- src/pkg/packager/common.go
- src/pkg/packager/create.go
- src/pkg/packager/deploy.go
- src/types/runtime.go
**Work Remaining:**
- backwards compatibility for this features is implicitly tested within `27_cosign_deploy_test.go` as that is deploying an older zarf package that still has the images in an `images.tar` tarball when deploying the `zarf-hello-world` games package.
> 1324 images tar now expanded

- docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
The documentation has a typo, where the markdown-link is missing the opening bracket
No related issue
> typo: Fix duplicate link

- src/test/e2e/07_create_git_test.go
This is a hotfix to remove the short sha check from git since this is not guaranteed to be 7 chars and can at times expand to 8.
Fixes #n/a
> Update create git test to remove short sha references

- src/pkg/utils/bytes.go
The commit swaps the message in the `title` variable to show the current bytes pulled in the progress bar instead of the expected total bytes. This improves the clarity of the message for the user.
https://github.com/defenseunicorns/zarf/issues/1439
Fixes #1439
> Update progress bar message

- docs/4-user-guide/3-zarf-schema.md
- src/pkg/packager/publish.go
- src/types/package.go
- src/ui/lib/api-types.ts
- zarf.schema.json
Fixes #1450 
This also adds `metadata.[]` of `authors`, `documentation`, `source`, `vendor`
Proof (showing README now appears + description)
> Add some extra manifest annotations on publish

- src/internal/packager/images/pull.go
- src/pkg/packager/network.go
The progress bar 'expected bytes' now takes duplicate layers into account
Fixes #1488
> update calculation for the expected bytes during image layer pulls

- src/pkg/packager/deploy.go
Fix package deploy error message when package and cluster architectures don't match
Fixes https://github.com/defenseunicorns/zarf/issues/1493
> Fix package deploy error message when package and cluster architectures don't match

- docs/4-user-guide/index.md
Documentation does not reflect the editorial guidelines outlined in the Project Style Guide. Editing the "User Guide" page to align with the updated Style Guide to improve readability for users.
- Remove excess '!'
- Remove metaphorical language
- Correct heading capitalization
- Edit context for better readability
- Add punctuation to lists
- Correct link text
Fixes #1510
> Docs edits to User Guide page

- src/cmd/tools/crane.go
- src/config/config.go
- src/internal/packager/images/common.go
- src/internal/packager/images/pull.go
- src/internal/packager/images/push.go
- src/pkg/packager/common.go
- src/pkg/packager/create.go
- src/pkg/packager/deploy.go
This ensures that ImgConfigs always carry their architecture down to Crane.
Fixes #N/A
> Pass package architecture around through ImgConfigs

- src/cmd/root.go
This hotfixes the root command to properly display help information when a bad command is entered
Fixes #N/A
> Fix root command help printing

- src/test/e2e/28_wait_test.go
Small fix to increase the timeout on our helm wait test
Fixes #N/A
> Increase the timeout for the helm wait test

- src/test/upgrade-test/previously_built_test.go
We should not check for deprecated text in the upgrade test.
Fixes #N/A
> No longer explicitly check for deprecated text in the upgrade test

- Dockerfile
This switches the Zarf agent base image to Chainguard static.
Fixes #1539
> Swap Dockerfile base image to Chainguard static

- examples/git-data/zarf.yaml
- src/test/e2e/07_create_git_test.go
This changes repo1 to github for the big bang repo in the git data test.
Fixes #N/A
> Change repo1 to GitHub to reduce CI flakes due to repo1 availability

- src/internal/packager/images/pull.go
- src/internal/packager/images/push.go
This enables some additional logging information for pushes to registries.
Relates to #1218
> Adding additional details for debugging about registry pushes

- Makefile
- docs/13-walkthroughs/5-big-bang.md
- examples/git-data/README.md
- examples/git-data/zarf.yaml
- src/extensions/bigbang/bigbang.go
- src/extensions/bigbang/bigbang_test.go
- src/test/e2e/07_create_git_test.go
This makes the requirement for the `bigbang` component officially 1.54.0 or greater.
N/A
> Officially require 1.54.0 or greater of Big Bang now

- README.md
- docs/0-zarf-overview.md
Fix README setup-zarf link and brew install commands on overview (combination of #1542 and #1543)
Fixes #N/A
> Fix README setup-zarf link and brew install commands on overview (combination of #1542 and #1543)

- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_init.md
- docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_deploy.md
- src/config/lang/english.go
Current Command descriptions are not specific to the consequences that command may have including 
Skips prompts to review SBOM
configure variables
select optional components 
review potential breaking changes.
Adds warning and more specific language to flag 
Updated to 
--Confirm  - Confirms package deployment without prompting. ONLY use with packages you trust. Skips prompts to review SBOM, configure variables, select optional components and review potential breaking changes.
...
Relates to #1600
> Update --confirm flag description for init and package deploy cmd

- src/extensions/bigbang/flux.go
This fixes an issue where when specifying a `repo` in the Big Bang extension (during `zarf package create`, causes a packaging related error.
```shell
ERROR:  Failed to create package: unable to process extensions: unable to process bigbang extension: unable to build kustomization: git cmd = '/usr/local/bin/git fetch --depth=1 origin 2.0.0-beta2': exit status 128
```
Here is a yaml snippet example for `zarf.yaml` that reproduces this error.
```yaml
kind: ZarfPackageConfig
metadata:
name: big-bang-example
description: "Deploy Big Bang Core"
version: 2.0.0-beta2
url: https://p1.dso.mil/products/big-bang
architecture: amd64
variables:
- name: DOMAIN
default: "bigbang.dev"
prompt: false
components:
- name: bigbang
required: true
extensions:
bigbang:
repo: …
```
> Fixes an issue where specifying repo for Big Bang extension fails

- src/pkg/packager/inspect.go
This fixes an issue where SBOMs from older packages are not unpacked correctly.
Fixes #1610
> Fix unpacking sboms issue from older Zarf packages

- examples/big-bang/config/disable-all.yaml
- examples/big-bang/config/kyverno.yaml
- examples/big-bang/config/loki.yaml
- examples/big-bang/zarf.yaml
- src/extensions/bigbang/manifests.go
- src/extensions/bigbang/test/package/disable-all.yaml
This adds support for Big Bang 2.0.0 (which was released today, Thursday April 20, 2023), and is backward compatible.  
N/A
> Big Bang 2.0 support

- src/extensions/bigbang/manifests.go
It appears that there is a mistake in the error handling of the semver.NewVersion function. It should be checking for no error instead of error. Found with @ragingpastry
Fixes #
Relates to #
> Fix: Failing Big Bang 2.0 Deployments

- docs/13-walkthroughs/3-deploy-a-retro-arcade.md
Just a small doc correction. Closes #1658 
Fixes #1658 
Relates to #1658
> [TASK] Update when to where in walkthrough docs

- src/pkg/utils/oras.go
tldr; Current ORAS client will query for scoped access to repo, regardless if credentials exist, resulting in a credential handshake attempt for public, non-authenticated resources, resulting in a failure.
> This behavior __must__ be tested in nightly, linking to the nightly issue
Fixes #1677
> 1677 getting an error when trying to pull from an oci registry unauthenticated

- docs/12-contribute-to-zarf/2-testing.md
- src/internal/cluster/state.go
- src/internal/packager/helm/chart.go
- src/internal/packager/images/push.go
- src/pkg/message/message.go
- src/pkg/utils/credentials.go
- src/test/common.go
- src/test/e2e/20_zarf_init_test.go
- src/test/e2e/24_variables_test.go
This fixes up our logging to sanitize on save as well as load state, not log imgconfigs and not log byte arrays.
Fixes #1655
> Fixup Zarf logging for sensitive vals and byte arrays

- .github/workflows/release.yml
This clears the zarf image cache before running a release to reduce disk pressure.
Fixes #N/A
> Clear the cache before running go releaser

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/tech_debt.md
- .github/ISSUE_TEMPLATE/ux_test.md
This refines our issue templates, adding more labels and gherkin where appropriate to better capture feature requests.
Fixes #N/A
- [N/A] Test, docs, adr added or updated as needed
> Improve GitHub issue templates (now with gherkin!)

- docs-website/static/docs/tutorials/package_create_wordpress.html
- docs-website/static/docs/tutorials/package_deploy_wordpress.html
- docs-website/static/docs/tutorials/package_deploy_wordpress_bottom.html
- docs/6-zarf-tutorials/0-creating-a-zarf-package.md
- docs/6-zarf-tutorials/2-deploying-zarf-packages.md
- examples/wordpress/README.md
- examples/wordpress/connect-services.yaml
- examples/wordpress/wordpress-values.yaml
- examples/wordpress/zarf.yaml
To make the docs more appealing to WordPress users spell the software name correctly with a capital P.
See e.g. https://developer.wordpress.org/reference/functions/capital_p_dangit/
---------
> Capitalize WordPress in docs correctly

- docs/2-the-zarf-cli/100-cli-commands/zarf_init.md
- src/config/lang/english.go
Update help text for --storage-class flag of zarf init
Fixes #1716
> Update help text for --storage-class flag of zarf init

- src/cmd/package.go
If there are variables in a config.json/toml and variables provided via the `--set` flag we need to ensure both the variable keys are uppercase before processing and templating them. At the moment we were only uppercasing the config file variable keys which resulted in inconsistent behavior  because of the indeterministic ordering of maps as we were looking for the variable's value.
Fixes #1726
> Ensure variables are uppercase 

- src/internal/cluster/injector.go
- src/pkg/k8s/images.go
- src/pkg/k8s/nodes.go
Checks to ensure that a node does not have a `NoSchedule` taint before choosing that node/image for the Zarf injector pod
Fixes #1730
Fixes #905
Gave this a WAG. It seems to work locally, but am unsure if this is the direction you guys want to go. Let me know!
> feat: add scheduling logic to zarf injector

- src/extensions/bigbang/bigbang.go
Flux has both `HelmRelease` and `HelmRepository` custom resources. Renaming this manifest for consistency with the kind of thing being created here. Since Big Bang now has an option to deploy with `HelmRepository` source this could be confusing to end users when deploying and reviewing the manifests in the zarf package.
No issue, just something I noticed while deploying.
> Rename helmrelease manifest file for BB extension

- renovate.json
This adds GitHub URLs to the regex matcher for renovate to update things like k3s.
Relates to #1754
> Add GitHub URLs in zarf.yamls to the renovate regex matcher

- src/pkg/packager/compose.go
- src/test/packages/51-import-everything/inception/zarf.yaml
Fix importing components that do not have any local resources via OCI.
Fixes #1772
> Fix Importing OCI Components w/ no local resources

- src/extensions/bigbang/bigbang.go
This PR makes it so that the Big Bang extension respects and uses the `onDeploy.defaults.maxTotalSeconds` field during its `onSuccess` actions to wait for HelmReleases to be ready.
The default time is still ten minutes (600s), but if a default is specified _and is greater than 600_, it will use that instead.
```yaml
components:
- name: bigbang
extensions:
bigbang:
version: 2.0.0
valuesFiles:
- config/disable-all.yaml
actions:
onDeploy:
defaults:
maxTotalSeconds: 1200 # 20 minutes in seconds
```
Fixes #1780
> Use action defaults MaxTotalSeconds during Big Bang deploy

- examples/component-actions/zarf.yaml
- src/test/e2e/02_component_actions_test.go
This fixes the cleanup of files in the parallel tests of component actions.
Fixes #N/A
> Properly remove files in parallel tests for component actions

- src/internal/packager/template/template.go
This fixes issues with generating an htpasswd for external registries (when it is not needed).
Fixes #1781
> Fix htpasswd issues

- .github/workflows/release.yml
- .github/workflows/test-upgrade.yml
- .goreleaser.yaml
- src/internal/cluster/state.go
- src/test/e2e/20_zarf_init_test.go
- src/test/packages/20-mismatched-arch-init/zarf.yaml
This PR reduces disk pressure further in the release and upgrade workflows and refactors the upgrade workflow to use ENV_VARs instead of manually editing the zarf-config.toml.
Fixes #N/A
> Reduce disk pressure in workflows

- src/pkg/message/message.go
- src/pkg/oci/utils.go
- src/pkg/packager/create.go
- src/pkg/packager/publish.go
- src/test/e2e/50_oci_package_test.go
Fixes `ReferenceFromMetadata` not properly receiving the `arch` suffix.
> Hotfix inline publish

- docs/2-the-zarf-cli/100-cli-commands/zarf_tools_registry_pull.md
- docs/2-the-zarf-cli/100-cli-commands/zarf_tools_registry_push.md
- src/cmd/tools/crane.go
- src/config/lang/english.go
Allow for internal crane pulls and pushes without a tunnel + explicit credentials
This gives the same ability as #1835 to `zarf tools crane push` and `zarf tools crane pull`.  Essentially, you shouldn't have to create a tunnel and auth to the registry to pull or push images to it.
#1835
> Allow for internal crane pulls and pushes without a tunnel + explicit auth

- src/internal/packager/helm/post-render.go
When deploying a yolo package, we still want the post-render logic to create all the namespaces for us. The `break` statement we had before was stopping before creating all of the namespaces.
> hotfix: create all namespaces, even when in yolo mode

- src/pkg/oci/common.go
- src/pkg/oci/pull.go
- src/pkg/oci/push.go
- src/pkg/oci/utils.go
- src/pkg/packager/publish.go
- src/test/common.go
- src/test/e2e/50_oci_package_test.go
- src/test/e2e/52_oci_compose_differential_test.go
Fixes what I broke.
This does re-architect some portions of OrasRemote and locks it down more. Everything in `*remote.Registry` is no longer exposed to outside usage and users of this remote client are restricted to the public receiver methods written in `pkg/oci`.
The context is now private as it really should not be edited outside of private receivers within OrasRemote.
During the writing of this PR I found out that ORAs already handles scopes at the request level and there is zero need to handle scopes yourself. I have not checked if I never had to do this, or if ORAs updated.
Fixes #1881 
Fixes #1795 
Fixes #1821
> Hotfix: only verify authentication to registry if creds exist

- src/cmd/root.go
- src/cmd/tools/common.go
- src/cmd/tools/crane.go
- src/cmd/tools/wait.go
- src/config/lang/english.go
- src/pkg/utils/exec/exec.go
Add ExitOnInterrupt utils function; catch interrupts when using wait
Add ability to catch interrupts when using wait command.
Fixes #1864
> Add ExitOnInterrupt utils function; catch interrupts when using wait

- .github/actions/install-tools/action.yaml
- .github/workflows/release.yml
This reduces disk pressure while running the release workflow.
Fixes #N/A
Relates to #
> Reduce the disk pressure for the release workflow

- .github/actions/cleanup-files/action.yaml
- .github/actions/install-tools/action.yaml
- .github/actions/packages/action.yaml
- .github/workflows/release.yml
- .github/workflows/test-bigbang.yml
- .github/workflows/test-k3s.yml
- .github/workflows/test-upgrade.yml
- Makefile
This PR refactors our larger workflows to use multiple jobs to avoid accumulation on disk.
Fixes #N/A
> Refactor large workflows into multiple jobs

- .github/actions/save-logs/action.yaml
- .github/workflows/test-bigbang.yml
- .github/workflows/test-upgrade.yml
- src/internal/packager/helm/repo.go
This fixes an issue with error returns when building the dependencies for a Helm chart.
Relates to #1875
> Fix the error return for building helm repositories

- Dockerfile
On clusters that strictly enforce no root containers via an Admission Controller, they can't determine that a named user isn't 0 in the container. This changes the container to identify the USER by UID and GID so the admission controller can allow this through.
Chainguard documents the UID and GID of nonroot https://edu.chainguard.dev/chainguard/chainguard-images/reference/static/overview/#users
Fixes #1921
> Use UID and GID for USER in Dockerfile

- src/cmd/tools/crane.go
- src/config/lang/english.go
- src/extensions/bigbang/test/package/flux-overrides-helm-controller.yaml
- src/extensions/bigbang/test/package/flux-overrides-kustomize-controller.yaml
- src/extensions/bigbang/test/package/flux-overrides-notification-controller.yaml
- src/extensions/bigbang/test/package/zarf.yaml
- src/internal/packager/helm/chart.go
This fixes an issue with zarf tools registry where an invalid cluster (one that was not connectable or did not have state) could cause a failure.
Fixes #1929
> Fix a bug with registry push/pull on detected but invalid clusters

- src/types/k8s.go
- src/ui/lib/api-types.ts
In `src/types/k8s.go` we are using than when it should be then for correct grammar
Fixes #1936 
Relates to #
> grammar, than to then

- src/cmd/prepare.go
- src/pkg/packager/prepare.go
Users using library code can benefit from receiving a [list of images ](https://github.com/defenseunicorns/zarf/blob/8d67f5fb2935ee9355786dfc0fd3b83efb6a8142/src/pkg/packager/prepare.go#L31). This was a feature request from the community. This provides users with the ability to pre-cache/pre-download images. 
Fixes #1918 
Relates to #
> return images as an array of strings for all components

- src/test/e2e/08_create_differential_test.go
- src/test/e2e/22_git_and_flux_test.go
- src/test/e2e/25_helm_test.go
- src/test/packages/08-differential-package/zarf.yaml
- src/test/packages/22-git-and-flux/zarf.yaml
Reduce the disk usage in tests by clearing the cache path for packages with images and simplifying the git data test
Fixes #N/A
> Reduce test disk usage and normalize git tests

- .github/workflows/nightly-eks.yml
- packages/distros/eks/eks.yaml
- packages/distros/eks/zarf.yaml
This upgrades the EKS cluster version to support Argo CD during nightly testing
Fixes #N/A
> Update EKS version to support Argo CD in nightly tests

- src/config/lang/english.go
- src/pkg/packager/common.go
- src/pkg/packager/common_test.go
Print a warning rather than return an error when an invalid CLIVersion is used when validating last non-breaking version
Fixes https://github.com/defenseunicorns/zarf/issues/1972
> Throw warning instead of error when default CLIVersion is used when validating last non-breaking version

- src/pkg/oci/pull.go
When pulling from GHCR we noticed that Zarf image manifests were coming from the `/manifests/` path when they should actually be coming from `/blobs/`. Even though they are technically image manifests, Zarf stores in them OCI as blobs, so this PR changes the MediaType on the image manifest to be a Zarf blob
> Ensure Zarf image manifests are pulled as blobs

- src/pkg/k8s/configmap.go
- src/pkg/k8s/namespace.go
- src/pkg/k8s/pods.go
- src/pkg/k8s/services.go
This fixes accidental label sharing when using Zarf as a library or in edge cases within Zarf itself.
Fixes #N/A
> Merge Common vars insteaad of using the global

- packages/zarf-registry/chart/templates/deployment.yaml
- packages/zarf-registry/chart/values.yaml
- packages/zarf-registry/registry-values.yaml
- packages/zarf-registry/zarf.yaml
Alter registry Helm chart to allow the PVC mount and filesystem storage driver to be toggled off.
Add extraEnvVars value and templating to helm chart to allow for arbitrary environment variables.
Add REGISTRY_PVC_ENABLED variable to registry package to toggle PVC creation and filesystem storage driver off/on.
Add REGISTRY_EXTRA_ENVS variable to registry package to expose extraEnvVars helm chart value.
Example of how to back the registry with S3:
```bash
zarf init --confirm --set REGISTRY_PVC_ENABLED=false --set REGISTRY_EXTRA_ENVS=' 
- name: REGISTRY_STORAGE
value: s3
- name: REGISTRY_STORAGE_S3_REGION
value: us-east-2
- name: REGISTRY_STORAGE_S3_BUCKET
value: registry-test-bucket-zarf
- name: REGISTRY_STORAGE_S3_ACCESSKEY
value: AKIAIOSFODNN7EXAMPLE
- name: REGISTRY_STORAGE_S3_SECRETKEY …
```
> feat: add extraEnvVars value to registry chart abd REGISTRY_EXTRA_ENVS to registry package

- src/pkg/transform/image.go
- src/pkg/transform/image_test.go
Checks if image.Host has already been patched
Fixes #1988
Relates to #
> Fix potential for double transform of images (i.e with operators that self-reference)

- .github/workflows/release.yml
- Makefile
- src/cmd/initialize.go
- src/cmd/tools/zarf.go
- src/config/lang/english.go
- src/pkg/oci/utils.go
- src/pkg/packager/common.go
- src/pkg/packager/publish.go
> 1773 Publish Zarf init + skeleton as OCI on release

- src/internal/packager/git/pull.go
- src/internal/packager/helm/post-render.go
- src/pkg/oci/utils.go
- src/pkg/packager/common.go
- src/pkg/packager/create.go
- src/pkg/utils/io.go
This PR resolves edge cases with `--tmpdir` behavior by always using the specified temp dir in commands and always making a unique sub folder for each zarf run.
Fixes #N/A
> Resolve edge cases with `--tmpdir` behavior

- docs/3-create-a-zarf-package/4-zarf-schema.md
- examples/variables/zarf.yaml
- src/cmd/common/viper.go
- src/config/lang/english.go
- src/internal/cluster/data.go
- src/internal/cluster/secrets.go
- src/internal/cluster/state.go
- src/internal/packager/helm/post-render.go
- src/internal/packager/validate/validate.go
- src/pkg/message/message.go
- src/pkg/message/progress.go
- src/pkg/packager/actions.go
- src/pkg/packager/prepare.go
- src/pkg/packager/variables.go
- src/test/e2e/24_variables_test.go
- src/test/packages/24-evil-variables/zarf.yaml
- src/types/component.go
- src/types/package.go
- src/ui/lib/api-types.ts
- zarf.schema.json
This PR introduces a new variable key that checks a set value against a regex pattern before being allowed to proceed.
Fixes #1997
> Initial implementation of pattern

- examples/component-actions/zarf.yaml
- src/pkg/packager/actions.go
- src/test/e2e/02_component_actions_test.go
This fixes an issue where the timeout message wouldn't show if retries was set to 0.
Fixes #N/A
> Adjust timeout messaging to be more correct on timeout errors with 0 retries

- src/pkg/oci/pull.go
This removes a check from find successors that would cause it to not find successors for manifests that are not images.
Fixes #N/A
> Remove the image manifest check from find successors

- adr/0017-zarf-bundle.md
This updates the bundle ADR to express that it was moved to UDS CLI instead.
Fixes #N/A
> update the bundle adr to express its migration to uds-cli

- docs/3-create-a-zarf-package/4-zarf-schema.md
- src/pkg/packager/deprecated/common.go
- src/test/e2e/01_component_choice_test.go
- src/types/component.go
- src/ui/lib/api-types.ts
- zarf.schema.json
Officially deprecate component `group` and add messaging to CLI + docs
Fixes #1792
> Officially deprecate component `group` and add messaging to CLI + docs

- .github/workflows/test-e2e.yml
- docs-website/src/components/SchemaItemProperties.js
- docs/3-create-a-zarf-package/2-zarf-components.md
- docs/3-create-a-zarf-package/3-zarf-init-package.md
- examples/helm-charts/README.md
- examples/manifests/README.md
- src/test/common.go
- src/test/e2e/00_use_cli_test.go
This adds a note about Zarf generating Helm Charts for the manifests you specify along with associated caveats.
Fixes #N/A
> Refine the documentation for `manifests`

- src/cmd/prepare.go
- src/config/lang/english.go
- src/pkg/packager/prepare.go
- src/test/e2e/00_use_cli_test.go
This changes the find image behavior to return an error if any charts failed to template during `zarf prepare find-images`
Fixes #1999
> Return an error after processing all charts if any of them failed during image discovery

- .github/workflows/test-e2e-shim.yml
- src/cmd/tools/crane.go
- src/internal/cluster/injector.go
- src/internal/packager/images/common.go
- src/internal/packager/images/pull.go
- src/internal/packager/images/push.go
- src/internal/packager/sbom/catalog.go
- src/internal/packager/sbom/viewer.go
- src/pkg/packager/create.go
- src/pkg/packager/deploy.go
- src/pkg/utils/image.go
- src/test/e2e/06_create_sbom_test.go
- src/test/e2e/26_simple_packages_test.go
- src/test/packages/26-image-dos-games/zarf.yaml
This allows shasum references to work with Zarf by swapping the crane tag parsing code with the docker library.
Fixes #1221
> Allow shasums to be present in images

- src/pkg/layout/component.go
- src/pkg/packager/deploy.go
- src/pkg/packager/mirror.go
- src/pkg/packager/publish.go
- src/pkg/packager/sources/cluster.go
- src/pkg/packager/sources/new.go
- src/pkg/packager/sources/oci.go
- src/pkg/packager/sources/split.go
- src/pkg/packager/sources/tarball.go
- src/pkg/packager/sources/url.go
- src/test/e2e/50_oci_package_test.go
Re-archives component tarballs during `package publish` as `LoadPackage` results in uncompressed component directories.
> Fix publish not publishing component tarballs

- src/extensions/bigbang/bigbang.go
- src/internal/packager/images/pull.go
- src/pkg/oci/common.go
- src/pkg/oci/pull.go
- src/pkg/oci/utils.go
- src/pkg/packager/compose.go
- src/pkg/packager/create.go
- src/pkg/packager/publish.go
- src/pkg/packager/pull.go
- src/pkg/utils/bytes.go
- src/pkg/utils/helpers/url.go
- src/test/e2e/50_oci_package_test.go
This improves the pull user experience and also introduces minor fixes for other UX bugs.
Fixes #2044
> Publish / pull UX improvement and minor fixes

- src/internal/cluster/tunnel.go
- src/pkg/k8s/pods.go
This moves a helper function for finding a containers port from a service pod into library code to be used by other binaries.
Relates to #1814
> Move find port function into library code

- src/cmd/initialize.go
- src/cmd/tools/crane.go
- src/config/lang/english.go
- src/internal/api/packages/find.go
- src/internal/cluster/data.go
- src/pkg/packager/actions.go
- src/pkg/utils/io.go
- src/pkg/utils/wait.go
This Pr normalizes Zarf command execution in Zarf so that the patterns work correctly when used as a library
Relates to #1814
Fixes #2026
> fix: normalize Zarf command handling in Zarf

- src/cmd/common/vendor.go
Another fix for Zarf UI split - this makes vendor commands aware of the Zarf command prefix.
Relates to #1814
> fix: add prefix understanding to IsVendorCmd

- examples/component-choice/README.md
- examples/component-webhooks/README.md
Updates `warn` to `caution` in webhooks docs
Fixes #N/A
> chore: update warn to caution in webhooks docs

- src/pkg/packager/create.go
If you try to template the value of `version` in a zarf.yaml and then create output to oci directly it fails due to checking the oci url before templating the file
```yaml
kind: ZarfPackageConfig
metadata:
name: example
version: "###ZARF_PKG_TMPL_VERSION###"
components:
- name: some-component
```
failing command:
`zarf package create --set VERSION=1.0 --output oci://somerepo:tag`
> fix not being able to template version when creating to oci directly

- src/internal/cluster/common.go
This hotfixes an issue with cluster connections failing to try to record package secrets if a cluster connection fails.
https://github.com/defenseunicorns/doug-translate/actions/runs/6505302332/job/17668716413?pr=4
Fixes #N/A
> fix: always return a nil on error during a cluster creation call

- .github/workflows/release.yml
This fixes an issue with the release workflow running out of space.
https://github.com/defenseunicorns/zarf/actions/runs/6514706543/job/17697026978
Fixes #N/A
> chore: add cleanup files action to push stage of release workflow

- .github/workflows/test-external.yml
- src/pkg/utils/yaml.go
- src/test/e2e/24_variables_test.go
- src/test/packages/24-evil-variables/zarf.yaml
Fix issues where the template regex does not match that of constants and variables.
Fixes #2074
> chore: fix numbers in package templates

- docs/12-contribute-to-zarf/2-testing.md
Document the use of -count=1 flag to disable test caching
N/A
> Document the use of -count=1 flag to disable test caching

- src/cmd/connect.go
removed the loop that kept calling `runtime.Gosched()`, it was trying to be nice, and yet using all the CPU time (1 thread) @jeff-mccoy please verify,
Fixes #1357
> fix: 1 CPU maxed out during zarf connect git

- packages/zarf-registry/zarf.yaml
This changes the registry wait command to wait for the full deployment of the registry rather than a pod to avoid race conditions during bootup.
Fixes #N/A
> wait for the registry deployment to be fully ready before continuing

- src/pkg/packager/composer/list.go
- src/pkg/packager/composer/list_test.go
This fixes variable and constant merging within component composability.
Fixes #2125
> fix: properly handle variable and constant merging

- packages/zarf-registry/chart/templates/_helpers.tpl
- packages/zarf-registry/chart/templates/configmap.yaml
- packages/zarf-registry/chart/templates/deployment.yaml
- packages/zarf-registry/chart/values.yaml
- packages/zarf-registry/registry-values.yaml
- packages/zarf-registry/zarf.yaml
- src/pkg/utils/io.go
Allows users to specify a CA bundle to the Registry when performing a `zarf init`.  
An example of how to use this to supply a Root CA Bundle in commercial AWS (although you don't need to):
Create a `zarf-config.yaml` similar to the following:
```yaml
package:
deploy:
set:
REGISTRY_CA_BUNDLE: my-custom-ca.pem
```
Initialize the cluster:
`ZARF_CONFIG=./zarf-config.yaml zarf init --confirm`
Fixes #2007
> feat: add REGISTRY_CA_BUNDLE variable to registry package and chart

- src/pkg/packager/common_test.go
Each test case in `TestValidateLastNonBreakingVersion()` updates a global variable `config.CLIVersion`, so the test cases should not be ran concurrently.
Fixes #2136
> fix: race condition bug in TestValidateLastNonBreakingVersion unit test

- .github/workflows/test-e2e-shim.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test-upgrade.yml
- Makefile
updated the makefile and the github action to reduce the work for non-cluster e2e tests. 
Fixes #
Relates to #
- [x ] Other (security config, docs update, etc)
- [x ] Test, docs, adr added or updated as needed
> fix: first step to split up the e2e need a cluster, versus ones that do not

- src/test/external/ext_in_cluster_test.go
- src/test/external/ext_out_cluster_test.go
Very small change to make sure that running the external tests locally do not just clobber a k3d cluster you might have running that uses the default name.
updated the test to use the same version of gitea as the one in the current zarf init
Fixes #
Relates to #
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] Test, docs, adr added or updated as needed
> fix: updated to not clobber whatever k3d cluster may be running, updated gitea to same version as zarf init

- src/internal/packager/images/push.go
- src/pkg/packager/create.go
- src/pkg/packager/deploy.go
- src/pkg/utils/helpers/misc.go
This adds better messaging when a retry occurs letting users better rectify flakes.
Fixes #N/A
> Add warnings for the errors encountered on retries

- docs/3-create-a-zarf-package/7-component-actions.md
- examples/component-actions/zarf.yaml
- src/internal/cluster/data.go
- src/pkg/packager/actions.go
- src/pkg/utils/exec/exec.go
- src/pkg/utils/wait.go
- src/test/e2e/02_component_actions_test.go
Adds `-e` to shells so that multiline actions fail faster. Noting that this only applies to [real shells](https://github.com/defenseunicorns/zarf/blob/356a4da121ae8cd0ffa720ab17ab859c5a2ac07a/src/pkg/utils/exec/exec.go#L173) 🤣 
EDIT: adding capability to Powershell based on comments below
Fixes https://github.com/defenseunicorns/uds-cli/issues/204
> fix: multiline actions fail faster

- docs/1-getting-started/0-understand-the-basics.md
- docs/2-the-zarf-cli/100-cli-commands/zarf_tools_helm_dependency.md
- docs/3-create-a-zarf-package/2-zarf-components.md
- docs/4-deploy-a-zarf-package/3-deployment-ui.md
- docs/4-deploy-a-zarf-package/5-k9s-dashboard.md
> docs fixes

- src/config/lang/english.go
- src/pkg/cluster/state.go
- src/pkg/packager/deploy.go
- src/test/common.go
- src/test/e2e/25_helm_test.go
- src/test/e2e/29_mismatched_checks_test.go
Slim down error messages
Fixes #1657
> chore: add message asking if the user has init'ed their cluster and slim down error messages more generally

- src/pkg/oci/fetch.go
When using Zarf's OCI client: `OrasRemote`, there is backwards compatibility to support previous package references. Old packages were published under image manifests, while new packages are published under image indexes. Resolving the manifest stored within an image index requires knowing which os/arch (`ocispec.Platform`) to search for.
All internal usages of this client properly use the `oci.WithArch` or `oci.WithPlatform` modifiers that add a `targetPlatform` to the client so that `r.ResolveRoot` is able to properly leverage `oras.ResolveOptions` and locate the correct manifest within the index.
However, if no platform modifier is used, `targetPlatform` remains `nil`. This causes `oras.Resolve` to return the descriptor of the index, not the manifest. To remedy this, simply error after …
> fix: `ResolveRoot` behavior

- src/pkg/cluster/injector.go
- src/pkg/k8s/images.go
Addresses https://github.com/defenseunicorns/zarf/issues/2144 to check if node has enough resources before the injector runs
Fixes #2144
> feat: check for available node resources before building injector pod

- src/internal/packager/images/pull.go
- src/pkg/utils/concurrency.go
Wait group was unnecessary in concurrencyTools, we are deleting it
> Deleting waitgroup from concurrencyTools

- src/pkg/packager/sources/validate.go
Handles a condition where execution would panic when a package contained no checksums.
Fixes https://github.com/defenseunicorns/zarf/issues/2261
> fix: handle panic during checksum validation

- packages/distros/k3s/common/zarf.yaml
- src/pkg/packager/deploy.go
- src/test/e2e/99_appliance_remove_test.go
This fixes ApplianceMode not being set and not triggering destroy scripts.
Fixes #2268
Relates to #2275
> fix: restore destroy script functionality

- renovate.json
This updates the renovate regex manager to one that can parse lists of charts, not just single chart entries.
Fixes #N/A
> chore: add a more robust chart search regexManager

- src/pkg/packager/actions.go
- src/test/e2e/02_component_actions_test.go
…s with no retries
Add check to see whether action failure was actually due to timeout or not. Currently Zarf reports an error of "timed out after 0 seconds" when a `cmd` within an action fails (with no retries) even if no timeout was set.
Fixes #2299
> fix: improve cmd failure messaging

- packages/gitea/zarf.yaml
- packages/zarf-registry/zarf.yaml
- src/test/e2e/20_zarf_init_test.go
https://github.com/defenseunicorns/zarf/pull/2180 introduced a bug and this PR removes the cause of the bug.
Actions conditionals are being added to Zarf in https://github.com/defenseunicorns/zarf/pull/2276 to allow these sort of checks to account for various use cases in a more clean way.
Also reopened https://github.com/defenseunicorns/zarf/issues/1824
Relates to https://github.com/defenseunicorns/zarf/issues/2273
> fix: revert storageclass checks for git server and seed registry

- docs/0-zarf-overview.md
- docs/12-contribute-to-zarf/2-testing.md
- docs/3-create-a-zarf-package/8-vscode.md
- docs/5-zarf-tutorials/0-creating-a-zarf-package.md
- docs/5-zarf-tutorials/9-resource-adoption.md
- docs/9-roadmap.md
- examples/helm-charts/zarf.yaml
- packages/logging-pgl/pgl-values.yaml
- src/internal/packager/git/gitea.go
- src/internal/packager/helm/utils.go
- src/pkg/k8s/services.go
- src/pkg/packager/actions.go
- src/pkg/packager/composer/list.go
- src/pkg/packager/lint/lint_test.go
- src/pkg/packager/sources/oci.go
- src/pkg/packager/sources/split.go
- src/pkg/packager/sources/tarball.go
- src/pkg/packager/sources/url.go
- src/pkg/packager/sources/validate.go
- src/pkg/utils/wait.go
- src/test/packages/25-local-tgz-chart/zarf.yaml
> Chore: fix spelling

- src/cmd/tools/helm/load_plugins.go
- src/pkg/cluster/state.go
- src/pkg/cluster/zarf.go
- Fixed Implicit memory aliasing in for loop - [gosec](https://github.com/securego/gosec) finding 
Fixes #
Relates to #
> chore: fix implicit memory aliasing in for loop

- src/internal/agent/http/server.go
- included timeout to avoid slowloris attack - `gosec` https://github.com/securego/gosec G112: Potential slowloris attack
Fixes #
Relates to #
> chore: configure agent server to avoid slowloris attack

- src/internal/packager/helm/common.go
- sorted go imports
Fixes #
Relates to #
> chore: sorted go imports

- examples/argocd/baseline/values.yaml
- examples/argocd/zarf.yaml
This fixes a test flake we see where we get TOOMANYREQUESTS on ECR pulls during CI runs on occasion. Example: https://github.com/defenseunicorns/zarf/actions/runs/8135568196/job/22230376242?pr=2292
> fix(ci): change ECR image to docker.io image

- src/pkg/oci/push.go
Added the OCI Image Index's mediaType for completeness sake per the OCI spec and to work around a known Sonatype Nexus Repository bug.
Fixes #2351
> fix: added OCI Image Index mediaType

- src/pkg/oci/common.go
- src/pkg/zoci/push.go
Small change to fix `publish`'s progress bar. The progress writer was not getting attached to the underlying client, leading to the progress bar never receiving the byte updates.
> fix: package publish progress bar frozen at zero

- .github/workflows/release.yml
- .goreleaser.yaml
- src/pkg/packager/publish.go
`zarf package publish <src>` would publish to CLI/runtime arch only and not respect source package's architecture, leading to packages existing at the wrong platform in the published index.
> fix(release): hotfix `publish` not respecting source package architecture

- packages/zarf-registry/registry-values.yaml
I added support for custom root CA Bundles to the registry some time back.  I encountered the need to do this again and discovered it was not properly formatting the cert in the registry configMap.  This minor change fixes that.
> fix: handle registry caBundle as a multiline string

- src/pkg/layout/sbom.go
- src/pkg/packager/deploy.go
- src/pkg/packager/mirror.go
- src/test/e2e/20_zarf_init_test.go
Refactoring that took place in https://github.com/defenseunicorns/zarf/pull/2223 introduced a bug on `deploy` where the user is not prompted to view SBOMs. This occurs because `p.sbomViewFiles` is not being populated correctly. This PR fixes this issue by populating `p.sbomViewFiles`.
N/A
> fix: populate `p.sbomViewFiles` on `deploy` and `mirror`

- src/pkg/packager/composer/list.go
- src/pkg/packager/creator/skeleton.go
Hotfixes skeleton publish. However, this breakage has revealed that the entire `skeleton` creation + publishing flow is flawed and requires an overhaul. Currently, while `skeleton` says it has an `arch` of `skeleton`, it is actually honoring the `--architecture` flag and resulting in a `skeleton` package that is single architecture. It is also not honoring `flavor`.
> fix: hotfix skeleton publish

- Makefile
- docs/3-create-a-zarf-package/6-package-sboms.md
`syft packages` was deprecated in favor of `syft scan` in `v0.100.0`
https://github.com/anchore/syft/pull/2446
https://github.com/anchore/syft/compare/v0.99.0...v0.100.0
> fix: update deprecated syft packages command to syft scan

- .github/workflows/commitlint.yml
Our OSSF scorecard workflow flagged this as a `Critical` security risk. Unsure of whether there is a real attack vector in our specific case. Using an environment variable to capture untrusted input in workflows is a documented security hardening best practice by GitHub as well.
This should also boost our OSSF scorecard score since we have a `0` on this check.
`Dangerous-Workflow` check:
- https://github.com/ossf/scorecard/blob/49c0eed3a423f00c872b5c3c9f1bbca9e8aae799/docs/checks.md#dangerous-workflow
Risk of script injections:
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
Example script injection attack:
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#example …
> fix: use env var for PR title in commitlint workflow to prevent untrusted script injection

- .github/workflows/scorecard.yaml
Zarf's branch protection was switched to rulesets instead of classic branch protection (temporarily in evaluate mode). A PAT is no longer needed. See: https://github.com/ossf/scorecard-action#authentication-with-fine-grained-pat-optional
> fix: use default GITHUB_TOKEN for ossf/scorecard-action

- src/internal/packager/images/pull.go
remove duplicate logic for writing image layers to disk concurrently
crane does this already in `WriteImage()`:
https://github.com/defenseunicorns/zarf/blob/08c92e12a4a2b05d0ea5abe055c7c01ba9964051/src/internal/packager/images/pull.go#L342
https://github.com/google/go-containerregistry/blob/8dadbe76ff8c20d0e509406f04b7eade43baa6c1/pkg/v1/layout/write.go#L333-L340
> fix: remove duplicate logic for writing image layers to disk concurrently

- docs/2-the-zarf-cli/100-cli-commands/zarf_dev_find-images.md
- src/cmd/dev.go
- src/config/lang/english.go
- src/pkg/packager/prepare.go
- src/types/runtime.go
For larger packages it can take a long time to parse through the cosign lookups, having an option to not do this is nice for faster feedback cycles.
Fixes #N/A
> feat: add option to skip cosign lookup during find images

- .github/actions/k3d/action.yaml
This PR pins the `k3s` image version used in our `k3d` action to the same version we use for the init package:
https://github.com/defenseunicorns/zarf/blob/02389274c61b59385ac339d6d690a148878427f9/packages/distros/k3s/zarf.yaml#L17
This is to workaround the containerd bug that tries to use HTTPS requests to pull images from Zarf's HTTP registry:
https://github.com/containerd/containerd/issues/10014
Related CI failures:
https://github.com/defenseunicorns/zarf/actions/runs/8621639619/job/23631060696?pr=2315
https://github.com/defenseunicorns/zarf/actions/runs/8619947296/job/23632023109?pr=2429
> ci: pin k3s image version in k3d github action

- site/astro.config.ts
fix: add redirect so old zarf base link is compatiable
Fixes NA
> fix: add redirect so old zarf base link is compatiable

- .gitignore
- README.md
- netlify.toml
redirect from docs change
Fixes #2441
> fix: readme dead links

- src/pkg/packager/creator/normal.go
- src/pkg/packager/creator/normal_test.go
Currently there is a bug wherein differential will only work if the source is a local file
> fix: differential package create with non local sources

- src/extensions/bigbang/test/bigbang_test.go
Unpin version in bigbang extension test
> test: unpin version in bigbang extension test

- Makefile
- go.mod
- go.sum
- hack/create-zarf-schema.sh
- src/cmd/internal.go
- zarf.schema.json
schema is broken due to unexpanded variables, expanding them now
> fix: broken schema from unexpanded embedded variables

- CODE_OF_CONDUCT.md
- README.md
It is generally good practice to have a code of conduct associated with a project (and will be a requirement if Zarf moves to a foundation). The [contributor covenant](https://www.contributor-covenant.org) is a good one to adopt that we can potentially adapt to our needs later down the line.
> docs: add contributor covenant code of conduct

- src/injector/src/main.rs
- zarf-config.toml
Looks like the media type of the registry:2.8.3 has been changed from `application/vnd.docker.distribution.manifest.v2+json` to  `application/vnd.oci.image.manifest.v1+json`. This breaks minikube, hence the current pipeline fails, as it will do a check to make sure the mediatypes match, which they don't since they're hardcoded
> fix: update docker media type in registry

- src/pkg/packager/common.go
Makes Packager's variableConfig publicly accessible which in turns allows access to VariableConfig's setVariableMap which is currently being used by uds-cli for bundle deployment processing.
Fixes #2472
> fix: adds GetVariableConfig function for packager

- src/pkg/packager/creator/differential_test.go
This change adds tests for remove copies from components to enable refactoring in the future.
Relates to #2337
> test: add tests for remove copies from components to enable refactoring

- site/src/content/docs/commands/zarf_package_inspect.md
- src/cmd/package.go
- src/config/lang/english.go
- src/pkg/packager/inspect.go
- src/test/e2e/06_create_sbom_test.go
- src/types/runtime.go
Adds `--list-images` to `zarf package inspect`.  Output is a YAML style list printed to STDOUT so it can be used with scripting.
Fixes https://github.com/defenseunicorns/zarf/issues/2479
> feat: inspect --list-images

- .github/workflows/scan-go-mod-tidy.yml
- .pre-commit-config.yaml
- Makefile
- hack/check-go-mod-tidy.sh
Adds a check in CI and `pre-commit` hooks to check if `go mod tidy` needs to be ran in a PR
This PR adds:
- shell script to check if `go mod tidy` needs to be ran in a PR
- `make` target to call the script
- workflow to run in CI
- `pre-commit` hook
> chore: add a check for go mod tidy

- zarf-config.toml
From `main`:
```shell
zarf p create . -a arm64 --confirm
```
Output:
or
```shell
curl -sLO https://zarf-public.s3-us-gov-west-1.amazonaws.com/injector/2024-05-03/zarf-injector-arm64
sha256sum ./zarf-injector-arm64 
```
Output:
```shell
866b5b1911dd920618be55164c4f95abe05753932ac6d0f2270d26e569d797a2  ./zarf-injector-arm64
```
The checksum does not match what is in our `zarf-config.toml`:
https://github.com/defenseunicorns/zarf/blob/e69f3ab70aa248d7cb43eda1b920d196b79188b1/zarf-config.toml#L10
> fix: use correct sha256 checksum for arm64 injector binary

- .github/actions/k3d/action.yaml
- .github/workflows/build-rust-injector.yml
- src/injector/.cargo/config.toml
- src/injector/Cargo.lock
- src/injector/Cargo.toml
- src/injector/Makefile
- src/injector/README.md
- src/injector/src/main.rs
- src/pkg/cluster/injector.go
- zarf-config.toml
> feat: update injector away from rouille to axum

- src/internal/agent/hooks/pods.go
- src/test/e2e/37_pod_without_labels_test.go
- src/test/packages/37-pod-without-labels/pod.yaml
identify when a pod has no labels (and thus has no `/metadata/labels` for jsonpatch replace operations. use the `add` jsonpath operation to add the labels path with the map[string]string value of `{"zarf-agent": "patched"}`
Fixes #2517 
Deploy a pod without labels to test:
```
apiVersion: v1
kind: Pod
metadata:
creationTimestamp: null
name: test
namespace: test
spec:
containers:
- image: nginx
name: test
resources: {}
dnsPolicy: ClusterFirst
restartPolicy: Always
status: {}
```
> fix(agent): missing path for pod without labels

- .golangci.yaml
- src/pkg/packager/filters/select.go
This change enables the ineffassign linter and fixes the only complaint by refactoring the select state filter.
Part of #2503 
Depends on #2499
> refactor: enable ineffassign linter

- src/cmd/package.go
- src/cmd/tools/crane.go
- src/pkg/cluster/zarf.go
- src/pkg/cluster/zarf_test.go
Adds test for GetDeployedPackage and GetDeployedZarfPackages
Relates to #2512
> test: cluster getDeployedPackages

- src/cmd/tools/zarf.go
- src/pkg/cluster/state.go
- src/pkg/cluster/state_test.go
Add tests for merge zarf state.
Relates to #2512
> test: add unit tests for merge zarf state

- site/astro.config.ts
- site/src/components/SkipLink.astro
Add Google Analytics for docs pages
Fixes n/a
> docs: add google analytics for docs pages

- Makefile
Fixes an issue where `make delete-packages` in the `cleanup-files` action of the release workflow deletes `src/pkg/packager/sources/testdata/zarf-package-wordpress-amd64-16.0.4.tar.zst`, causing `git` to be in a dirty state and the workflow to fail.
https://github.com/defenseunicorns/zarf/actions/runs/9216112744/job/25356360304#step:11:92
> fix(release): do not delete testdata in release workflow

- src/pkg/packager/sources/new_test.go
- src/pkg/utils/network_test.go
Shutdown HTTP test servers with `Close()`
Noticed we aren't shutting down HTTP test servers in a couple of our unit tests while working on #2558
> test: shutdown http test servers

- src/pkg/cluster/state.go
- src/pkg/cluster/state_test.go
This change adds tests to Zarf init state. It also fixes bugs that were found during testing. 
* Existing Zarf namespace would receive agent ignore label
* Existing Zarf namespace would not receive managed by label
* Clusters with zero nodes would cause panic
Relates to #2550
> test: zarf init state

- src/pkg/packager/common_test.go
- src/test/e2e/29_mismatched_checks_test.go
Removes `TestMismatchedArchitectures` e2e test and refactors `TestValidatePackageArchitecture` unit test
Relates to #2562
> test: remove validate pkg arch e2e test

- src/cmd/root.go
This change adds some custom logic for printing returned errors from Cobra commands. This will allow embedded tools like Helm to behave the same as the original tools. While the Zarf commands will print errors in the same expected error format.
Relates to #2567
> fix: add custom error printing for Zarf commands

- src/internal/agent/http/server.go
- src/internal/agent/start.go
Updates the agent to use ctx from the root
> refactor: use root ctx in agent

- src/internal/packager/template/template.go
- src/pkg/variables/common.go
- src/pkg/variables/templates.go
> chore: deprecate DeprecatedKeys

- SUPPORT.md
- adr/0007-use-rust-binary-for-both-injection-stages.md
- adr/0012-local-image-support-via-docker.md
- adr/0017-zarf-bundle.md
- adr/0020-package-sources.md
- adr/0024-starlight.md
- packages/zarf-registry/chart/templates/hpa.yaml
- src/cmd/tools/helm/root.go
- src/pkg/cluster/tunnel_test.go
- src/pkg/message/handler.go
I identified some typos while diving through the repo.
> chore: fix typos

- go.mod
Updates Go version to the latest stable version of `1.22`
https://go.dev/dl/
> chore: update go version to 1.22.4

- src/cmd/version.go
Fixes version command error handling.
N/A
> fix: handle errors in version command

- Makefile
- src/test/e2e/main_test.go
Simplify `TestMain` and update the `build-examples` make target to build only the binary for the local system.
Relates to #2562
> test: cleanup e2e tests

- .golangci.yaml
- src/internal/agent/http/admission/handler.go
- src/internal/agent/http/proxy.go
- src/internal/agent/http/server.go
- src/pkg/cluster/state_test.go
- src/pkg/cluster/zarf_test.go
- src/pkg/message/message.go
- src/pkg/packager/lint/lint.go
- src/pkg/packager/sources/new_test.go
- src/pkg/utils/network_test.go
- src/pkg/variables/templates_test.go
- src/pkg/zoci/push.go
- src/test/nightly/ecr_publish_test.go
This change enables the errcheck linter which requires all returned errors to be checked.
Part of #2503
Depends on #2499
> refactor: enable errcheck linter

- src/cmd/tools/crane.go
During refactoring in #2460 we broke the option parameters for Crane. Honestly I am not surprised that this has happened. The way that these options are parsed and passed around are a threading mess. The issue is that this seems to also be the method in which Crane does it. This change reverts the specific pointer changes which caused the issue in the first place.
This is one the reasons why I do not like Cobra. The use of init functions and global variables are doomed to cause threading issues. Reminds me of writing Java programs with Spring Boot.
Fixes #2571
> fix: crane option argument parameters

- src/internal/packager/sbom/catalog.go
When creating an image SBOM with syft, we currently pass an empty string `""` to `NewFromStereoscopeImageObject` when creating a new image source object.
```go
source.NewFromStereoscopeImageObject(syftImage, "", nil)
```
The second argument is the image reference. This data is ultimately used to populate the source metadata in the final SBOM, but since we pass an empty string, the `userInput` field is empty.
The fix is to pass in the image reference so that the `userInput` field is populated in the final SBOM.
```go
source.NewFromStereoscopeImageObject(syftImage, ref, nil)
```
Steps to reproduce:
1. Create this package
```yaml
kind: ZarfPackageConfig
metadata:
name: sbom-test
architecture: amd64
components:
- name: sbom-test
required: true
images:
- …
```
> fix: pass image reference to syft sbom source object

- Makefile
This PR updates the `init-package` make target to ensure it builds only the binary appropriate for the local system
> fix: only build a single binary in the init-package make target

- examples/kiwix/zarf.yaml
s3 we were using for examples was broken
> fix: using a new s3 backend for test data

- src/internal/packager/helm/zarf.go
This PR splits out a refactor that was done in #2625
https://github.com/defenseunicorns/zarf/pull/2625#discussion_r1644994882
Here is some context for why I refactored `UpdateZarfAgentValues`.
In our e2e test suite, `TestConnectAndCreds` runs `zarf tools update-creds --confirm`.
`update-creds` calls `UpdateZarfAgentValues` which used to delete all agent pods manually based on label selector and immediately return without waiting for the pods to be ready. `TestMetrics` is ran immediately after `TestConnectAndCreds`, and it attempts to establish a tunnel connection to the Zarf agent to test the /metrics endpoint. This test was failing because there were no running agent pods yet after deleting them. This is not a problem in our tests right now because we run assertions against the logging …
> refactor: change UpdateZarfAgentValues to rolling restart

- go.mod
- src/internal/packager/images/pull.go
- src/pkg/packager/deploy.go
Adds *some* context to pull. Pull still won't cancel until 10 images are pulled unless context is cancelled before the pull starts since crane doesn't take context.
Data injections will now not retry after context is cancelled
Relates to #2647
> feat: add context to pull and data injections

- go.mod
- go.sum
Patches CVE-2024-6104
Fixes https://github.com/defenseunicorns/zarf/security/dependabot/128
> chore: patch CVE-2024-6104

- examples/kiwix/manifests/deployment.yaml
- site/src/content/docs/ref/components.mdx
Data Injections have a very hidden functionality in that they only work if the `###ZARF_DATA_INJECTION_MARKER###` variable is in the pod spec. This documents that functionality.
> docs: data injection

- go.mod
- go.sum
- src/internal/agent/hooks/flux-helmrepo.go
- src/internal/agent/hooks/flux-ocirepo.go
#2005 was merged with helpers/v1, whoops
> fix: remove helpers v1

- src/cmd/dev.go
- src/cmd/initialize.go
- src/cmd/package.go
- src/cmd/tools/zarf.go
- src/internal/agent/http/server.go
- src/internal/agent/start.go
- src/internal/packager/helm/repo.go
- src/pkg/cluster/state.go
- src/pkg/cluster/state_test.go
- src/pkg/message/message.go
- src/pkg/message/spinner.go
- src/pkg/packager/common.go
- src/pkg/packager/deploy.go
- src/pkg/packager/deploy_test.go
- src/pkg/pki/pki.go
This completely removes the use of any Fatal command which would immediately exit the program. Use of the function has been replaced with returning errors. 
Depends on #2664
Relates to #2558
> refactor: remove message.Fatal and spinner.Fatal

- src/pkg/packager/common.go
- src/pkg/packager/common_test.go
- src/pkg/packager/create.go
- src/pkg/packager/deploy.go
- src/pkg/packager/dev.go
- src/pkg/packager/inspect.go
- src/pkg/packager/interactive.go
- src/pkg/packager/mirror.go
- src/pkg/packager/prepare.go
- src/pkg/packager/publish.go
- src/pkg/packager/remove.go
This change removes warnings as a property in packager. Instead a local variable is used where warnings are actually needed. 
Relates to #2338
> refactor: remove warnings property from packager

- src/pkg/packager/common.go
- src/pkg/packager/create.go
- src/pkg/packager/deploy.go
- src/pkg/packager/interactive.go
- src/pkg/packager/mirror.go
Removes the sbom view fiels struct property.
Part of #2694
> refactor: remove sbom view files property from packager

- src/cmd/dev.go
- src/internal/agent/hooks/argocd-application.go
- src/internal/agent/hooks/argocd-repository.go
- src/internal/agent/hooks/flux-gitrepo.go
- src/internal/agent/hooks/flux-helmrepo.go
- src/internal/agent/hooks/flux-ocirepo.go
- src/internal/agent/hooks/pods.go
- src/internal/agent/http/admission/handler.go
- src/internal/agent/start.go
- src/pkg/cluster/data.go
- src/pkg/cluster/secrets.go
- src/pkg/cluster/state.go
- src/pkg/message/connect.go
- src/pkg/message/message.go
- src/pkg/utils/cosign.go
- src/pkg/utils/io.go
- src/pkg/utils/yaml.go
- src/test/e2e/05_tarball_test.go
This change removes unused functions in message. It also moves some of the logic out of message because it is the wrong place to live. Additionally I have removed some debug logs which are basically used as tracing. 
Relates to #2588
> refactor: remove unused message functions and verbose logging

- src/pkg/packager/lint/lint.go
- src/pkg/packager/lint/lint_test.go
Removes unpinned image warning generated by `zarf dev lint` for cosign signatures.
...
Fixes #2577 
- [ x ] Test, docs, adr added or updated as needed
- [ x ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/.github/CONTRIBUTING.md#developer-workflow) followed
> fix: remove unpinned image warning in lint for cosign signatures

- .github/pull_request_template.md
Correct link to CONTRIBUTING.md in PR template.
> fix: fix link to CONTRIBUTING.md in PR template

- src/pkg/packager/deploy.go
This change ensures the local cluster service format regexp is compiled just once on program's startup.
I believe similar cases might be found and improved across the codebase.
> refactor: compile local cluster service format regexp just once

- .github/workflows/build-rust-injector.yml
- Makefile
updates the s3 injector to publish from main to a defense unicorn repo
> chore: update s3 injector

- .github/workflows/publish-application-packages.yml
- .github/workflows/release.yml
- .github/workflows/test-upgrade.yml
- Makefile
- src/config/config.go
- src/pkg/zoci/utils.go
- src/test/e2e/08_create_differential_test.go
- src/test/e2e/11_oci_pull_inspect_test.go
- src/test/e2e/13_find_images_test.go
- src/test/e2e/14_create_sha_index_test.go
- src/test/e2e/21_connect_creds_test.go
- src/test/packages/00-remote-pull-fail/zarf.yaml
- src/test/packages/08-differential-package/zarf.yaml
- src/test/packages/14-index-sha/image-index/zarf.yaml
- zarf-config.toml
This change renames the image references to the new Zarf Dev.
Relates to #2732
> refactor: rename image references

- .github/workflows/build-rust-injector.yml
- .github/workflows/dummy-dco.yaml
- examples/git-data/zarf.yaml
- src/pkg/packager/lint/lint_test.go
- src/test/e2e/07_create_git_test.go
- src/test/e2e/09_component_compose_test.go
- src/test/e2e/22_git_and_gitops_test.go
- src/test/packages/09-composable-packages/sub-package/zarf.yaml
- src/test/packages/09-composable-packages/zarf.yaml
- src/test/packages/12-lint/zarf.yaml
- src/test/packages/22-git-data/zarf.yaml
old link was archived, this should be owned by the zarf-dev org anyway.
The numbers changing in this pr are crc hashes that are changing because the repo name changed.
> chore: move public test repo

- src/cmd/dev.go
- src/extensions/bigbang/bigbang.go
- src/internal/packager/git/clone.go
- src/internal/packager/git/pull.go
- src/internal/packager/helm/repo.go
- src/pkg/packager/creator/normal.go
- src/pkg/packager/generate.go
- src/pkg/packager/prepare.go
> chore: move context.TODO to context.Background()

- src/pkg/cluster/data.go
- src/pkg/packager/deploy.go
This changes the data injection signature to defer parallelization to the caller, enabling it to return errors. It also replaces the wait group with a error group to handle the errors. 
Relates to #2719
> fix: data injection to return errors

- src/types/package.go
- zarf.schema.json
This reverts commit ed2f876dc0ff2fed647b64d62f5a0843d41eed75.
We received feedback that people do have uses for the .metadata.images field. Adding it back
> feat: revert "feat: remove .metadata.image from schema (#2606)"

- .github/workflows/nightly-ecr.yml
- .github/workflows/nightly-eks.yml
- packages/distros/eks/eks.yaml
- packages/distros/eks/zarf.yaml
- src/test/nightly/ecr_publish_test.go
Nightly jobs are currently broken, this moves them off of a personal AWS account to a defense unicorns supported account. Also only running cluster tests on eks as the non cluster tests don't care about the distro
> chore: update permissions for eks & ecr nightly tests

- src/cmd/common/setup.go
- src/cmd/root.go
- src/cmd/tools/common.go
- src/cmd/version.go
- src/config/config.go
- src/config/lang/english.go
- src/pkg/message/message.go
- src/pkg/utils/yaml.go
This change refactors the setup CLI to only run once in the root command. Additionally it adds error returns and removes use of global configuration variables.
> refactor: move setup CLI to only run once in root command

- src/extensions/bigbang/bigbang.go
- src/internal/packager/helm/chart.go
- src/internal/packager/helm/post-render.go
- src/internal/packager/helm/zarf.go
- src/pkg/packager/deploy.go
- src/pkg/packager/prepare.go
Relies on #2746 before merging 
This messes with some public functions, I ran them through UDS-CLI to make sure we aren't breaking anything.
> chore: move context.TODO to context.Background() (3)

- src/internal/packager/sbom/tools.go
- src/pkg/packager/creator/normal.go
- src/pkg/packager/inspect.go
This refactors ViewSBOMFiles to handle errors properly. This was initially done to stop debug logging the single error, but it felt wrong to not fix the other errors while I was at it.
> refactor: add error handling to view SBOM files

- src/cmd/dev.go
- src/internal/packager/helm/repo.go
- src/pkg/packager/creator/normal.go
- src/pkg/packager/prepare.go
- src/pkg/packager/sources/url.go
- src/pkg/utils/network.go
- src/pkg/utils/network_test.go
- src/test/e2e/50_oci_publish_deploy_test.go
- src/test/external/ext_in_cluster_test.go
- src/test/external/ext_out_cluster_test.go
- src/test/helpers/helpers.go
- src/test/testutil/testutil.go
Last one! 
Relies on #2746, #2747, #2748 
Implements a global "testing util" under test/helper - open to naming ideas or different implementations. This allows for `TestContext(t *testing.T) context{}` to be used by any test, and overtime we can place more things in here.
> chore: move context.TODO to context.Background() (5)

- src/internal/agent/hooks/argocd-application.go
- src/internal/agent/http/admission/handler.go
- src/internal/agent/http/server.go
- src/internal/agent/operations/hook.go
- src/internal/packager/git/checkout.go
- src/internal/packager/git/gitea.go
- src/internal/packager/helm/chart.go
- src/internal/packager/helm/images.go
- src/internal/packager/helm/post-render.go
- src/internal/packager/images/push.go
- src/pkg/cluster/tunnel.go
- src/pkg/packager/common.go
- src/pkg/packager/creator/compose.go
- src/pkg/packager/creator/normal.go
- src/pkg/packager/creator/skeleton.go
- src/pkg/packager/prepare.go
- src/pkg/packager/sources/new.go
- src/pkg/packager/sources/oci.go
- src/pkg/utils/io.go
- src/pkg/utils/network.go
- src/test/e2e/00_use_cli_test.go
This change removes verbose debug logs in preparation for the logging refactoring.
> refactor: remove overly verbose debug logs

- src/config/lang/english.go
- src/internal/agent/hooks/pods.go
- src/internal/agent/http/proxy.go
- src/internal/packager/git/checkout.go
- src/internal/packager/git/push.go
- src/pkg/packager/actions/actions.go
This change replaces instances of logging warnings for errors with returning errors instead.
> refactor: replace warning logs with returning errors

- .golangci.yaml
- src/cmd/common/viper.go
- src/extensions/bigbang/bigbang.go
- src/internal/packager/helm/chart.go
- src/internal/packager/helm/post-render.go
- src/internal/packager/helm/repo.go
- src/pkg/layout/component.go
- src/pkg/packager/sources/oci.go
- src/pkg/packager/sources/split.go
- src/pkg/packager/sources/tarball.go
- src/pkg/utils/yaml.go
This change enables the errlint linter and fixes any violations.
N/A
> fix: error formatting and comparison and enable errorlint

- .github/.codecov.yml
This should turn off annotations and set success threshold to 1%
> chore: turn down codecov

- src/pkg/packager/common.go
- src/types/package.go
- src/types/package_test.go
This change moves `HasImages` to the Zarf package struct. It also adds tests for some of the packages methods.
Relates to #2709
> refactor: move and test HasImages

- examples/podinfo-flux/git/podinfo-kustomization.yaml
- examples/podinfo-flux/git/podinfo-source.yaml
- src/test/external/docker-compose.yml
We were getting warnings that we should update to v1 with flux git repos and that the docker compose version key is obsolete
> chore: update obsolete versions

- src/pkg/cluster/zarf.go
- src/pkg/packager/common.go
- src/pkg/packager/deploy.go
This change moves generation from a struct property in packager to the only place where it is needed.
Relates to #2709
> refactor: move package generation to a local variable

- src/cmd/connect.go
- src/pkg/packager/deploy.go
This change replaces more debug logs with returning errors instead.
> refactor: replace debug logs with returning errors

- src/pkg/packager/creator/creator_test.go
- src/pkg/packager/prepare.go
- src/pkg/packager/prepare_test.go
- src/test/testutil/schema.go
- src/test/testutil/testutil.go
This change adds tests to FindImages to enable refactoring of returning errors.
N/A
> test: add tests for FindImages

- .github/workflows/release.yml
- .grype.yaml
During some cleanup in #2802 we broke the release pipeline because we did not see that Grype was still being used during the release. This change reintroduces installation of Grype in the release workflow.
N/A
> fix: install grype during release

- .github/workflows/test-shim.yml
We recently changed the names of the jobs in github actions. Previously most were named validate, which made them hard to require / not require separately. We need to add the renamed actions to the shim so that they pass the required checks when a documentation PR is created
> ci: add renamed github workflow jobs to the shim workflow

- go.mod
- go.sum
- src/internal/packager/helm/chart.go
- src/internal/packager/images/pull.go
- src/internal/packager/images/push.go
- src/pkg/cluster/cluster.go
- src/pkg/cluster/data.go
- src/pkg/cluster/namespace.go
- src/pkg/cluster/state.go
- src/pkg/cluster/tunnel.go
- src/pkg/cluster/zarf.go
- src/pkg/packager/actions/actions.go
- src/pkg/packager/deploy.go
- src/test/e2e/35_custom_retries_test.go
This change replaces the different retry implementations with only using go-retry.
Part of #2827  
> fix: replace helpers.Retry with go-retry and adjust delay

- .golangci.yaml
- src/extensions/bigbang/test/bigbang_test.go
- src/pkg/lint/validate.go
- src/pkg/packager/prepare.go
The linter version was upgraded but somehow the rules passed to this fixes the warnings which are now failing.
N/A
> fix: linter warnings in new Golang CI version

- src/pkg/packager/prepare.go
- src/pkg/packager/prepare_test.go
- src/pkg/packager/testdata/find-images/agent/deployment.yaml
- src/pkg/packager/testdata/find-images/agent/zarf.yaml
- src/pkg/packager/testdata/find-images/helm-chart/chart/.helmignore
- src/pkg/packager/testdata/find-images/helm-chart/chart/Chart.yaml
- src/pkg/packager/testdata/find-images/helm-chart/chart/templates/NOTES.txt
- src/pkg/packager/testdata/find-images/helm-chart/chart/templates/_helpers.tpl
- src/pkg/packager/testdata/find-images/helm-chart/chart/templates/deployment.yaml
- src/pkg/packager/testdata/find-images/helm-chart/chart/templates/hpa.yaml
- src/pkg/packager/testdata/find-images/helm-chart/chart/templates/ingress.yaml
- src/pkg/packager/testdata/find-images/helm-chart/chart/templates/service.yaml
- src/pkg/packager/testdata/find-images/helm-chart/chart/templates/serviceaccount.yaml
- src/pkg/packager/testdata/find-images/helm-chart/chart/templates/tests/test-connection.yaml
- src/pkg/packager/testdata/find-images/helm-chart/chart/values.yaml
- src/pkg/packager/testdata/find-images/helm-chart/values.yaml
- src/pkg/packager/testdata/find-images/helm-chart/zarf.yaml
- src/pkg/packager/testdata/find-images/invalid-helm-repo/zarf.yaml
- src/pkg/packager/testdata/find-images/invalid-manifest-yaml/deployment.yaml
- src/pkg/packager/testdata/find-images/invalid-manifest-yaml/zarf.yaml
- src/test/e2e/13_find_images_test.go
This removes warning logs and replaces it with returning the errors immediatly.
Relates to #2849
> refactor: findImages to return errors immediately

- src/pkg/cluster/data.go
This change removes the retrying in data injections, as it does not have any effect. The current implementation will only retry at a single condition which is when the pods returned from the wait function is empty.
https://github.com/zarf-dev/zarf/blob/0943d76b25464ab7ad948b4c93957b22d966c02b/src/pkg/cluster/data.go#L88-L90
This event wont actually happen because the wait logic will run until the context cancelled if the pod list is empty. This means that returning an empty list is impossible.
Removing the nested retry implementation increases legibility. 
Depends on #2856
> refactor: remove unnecessary retry logic from data injection

- src/cmd/tools/zarf.go
- src/pkg/cluster/secrets.go
- src/pkg/cluster/secrets_test.go
This change replaces warning logs with returning errors when updating Zarf managed secrets.
> refactor: store managed secrets and add tests

- packages/zarf-registry/zarf.yaml
- src/test/e2e/00_use_cli_test.go
- zarf-config.toml
Injector is pointed to govcloud account which is down atm, it should be in the defenese unicorn account anyway
> fix: update injector

- src/cmd/tools/zarf.go
- src/config/lang/english.go
- src/pkg/cluster/zarf.go
- src/pkg/cluster/zarf_test.go
- src/test/e2e/21_connect_creds_test.go
- src/test/e2e/99_appliance_remove_test.go
This PR fixes a bug where Zarf will error when the git server or artifact server doesn't exist and `zarf tools update-creds` is run
Fixes #2903
> fix: update creds not breaking when internal git server not deployed

- examples/helm-charts/zarf.yaml
- src/cmd/root.go
- src/internal/packager/helm/chart.go
- src/test/e2e/09_component_compose_test.go
- src/test/e2e/20_zarf_init_test.go
- src/test/e2e/31_checksum_and_signature_test.go
- src/test/e2e/34_custom_init_package_test.go
In a recent change, we stopped giving the helm install error as a warning to users. 
I considered keeping it a warning or appending it to the other errors. The warning looked nicer, but only because newlines look weird with how are error messages are formatted in pterm. Changed the error message to be paragraphed and went with that.
warning: 
error: 
error (paragraph formatting):
Fixes: #2907
> feat: better error message on helm fail

- .pre-commit-config.yaml
- src/pkg/lint/lint.go
- src/pkg/lint/lint_test.go
- src/pkg/lint/schema.go
- src/pkg/lint/schema_test.go
- src/pkg/lint/testdata/package-with-templates/zarf.yaml
- src/pkg/packager/creator/normal.go
- src/pkg/packager/creator/skeleton.go
- src/pkg/packager/creator/utils.go
- src/pkg/packager/dev.go
We are currently not evaluating templates on schema creation, this can lead to issues if templates are used where there are regex patterns in the schema. This fixes it to evaluate templates on schema creation
Fixes #2908
> fix: evaulate templates on schema check

- .github/workflows/publish-application-packages.yml
> ci: id-token write application packages

- examples/composable-packages/zarf.yaml
- site/src/content/docs/getting-started/index.mdx
- src/test/e2e/09_component_compose_test.go
- src/test/e2e/12_lint_test.go
- src/test/e2e/27_deploy_regression_test.go
- src/test/packages/12-lint/linted-import/zarf.yaml
- src/test/packages/12-lint/zarf.yaml
Since we replaced the cosign key the dos games example in the docs won't work. We released a new dos-games package with the new private key and changed the docs references to those
> docs: update dos games example

- src/pkg/packager/common.go
- src/pkg/packager/deploy.go
- src/pkg/packager/generate.go
- src/pkg/packager/inspect.go
- src/pkg/packager/interactive.go
- src/pkg/packager/pull.go
- src/pkg/packager/remove.go
This change removes use of named returns from packager. The purpose of this is to make it easier for future refactoring that will eventually lead to breaking out `printTablesForDeployment` outside of this package.
> refactor: remove use of named returns in packager

- src/internal/packager/helm/repo.go
- src/test/e2e/25_helm_test.go
This change removes fetching the Chart index and listing available Helm charts and versions when the Chart is not found.
> refactor: remove printing available Helm charts and versions when the Chart is not found

- src/pkg/cluster/zarf.go
- src/pkg/packager/common.go
- src/pkg/packager/deploy.go
- src/pkg/packager/dev.go
- src/types/k8s.go
This change moves the connect strings map to the installed charts struct. This removes potential race conditions that could be caused by multiple threads writing to the same struct property.
Depends on #2940
> refactor: remove connect strings from packager property

- .github/workflows/test-import.yaml
The test-imports workflows break when called from a fork
fixes #2952
> fix(ci): test-imports workflow breaks when called from a fork

- go.mod
- site/src/content/docs/commands/zarf_dev_deploy.md
- site/src/content/docs/commands/zarf_init.md
- site/src/content/docs/commands/zarf_package_deploy.md
- site/src/content/docs/ref/components.mdx
- src/api/v1alpha1/component.go
- src/api/v1beta1/component.go
- src/config/lang/english.go
- src/pkg/packager/composer/list.go
- src/pkg/packager/composer/list_test.go
- src/pkg/packager/deploy.go
- src/pkg/packager/deploy_test.go
- src/pkg/packager/prepare.go
- src/test/e2e/36_health_check_test.go
- src/test/packages/36-health-checks/ready-pod.yaml
- src/test/packages/36-health-checks/zarf.yaml
- zarf.schema.json
This change adds a new `healthChecks` field which will verify the health of any resource after deployment. This PR does not affect the current wait logic in actions, both exist simultaneously.
Relates to #2203
> feat: add health checks

- site/src/content/docs/roadmap.mdx
Reading the roadmap it appears the docs site is built with [astro](https://astro.build/) not [docusaurus](https://docusaurus.io/).
This PR marks the item as checked on the docs page.
Requires confirmation!
no issue
> docs: update docs item in update Q2 roadmap

- src/internal/packager/images/push.go
This PR fixes the CLI flashing when pushing images. This can be seen in the linked gif in the issue #2651
Fixes #2651
> fix: progress bar image name flashes on push

- src/pkg/packager/composer/list_test.go
- src/pkg/packager/composer/override.go
Ensures imported components merge Helm override variables, similar to the existing behavior with `valueFiles`.
Also updated the hint behavior to only add hints on root level keys, which was causing an issue when accounting for [this hint](https://github.com/zarf-dev/zarf/blob/main/src/pkg/packager/interactive.go#L111) which I believe was erroneously appearing in the tests alongside Helm overrides `variables`.
Fixes https://github.com/zarf-dev/zarf/issues/2966
> fix: imported helm overrides

- src/cmd/common/viper.go
Don't output the `NOTE` on config file usage if there is no config file set.
Currently `zarf version` [will not go through the process of setting the configuration file](https://github.com/zarf-dev/zarf/blob/efa306fdcbe605ec6d17f4cf72c707f7227af52a/src/cmd/common/viper.go#L122-L124), but the root cmd code path still has a part where it calls `printViperConfigUsed()` and tries to print it. As a result you get empty output, even if you have a valid config available:
In this PR we simply omit the config file note if we have no config file set. The [printViperConfigUsed()](https://github.com/zarf-dev/zarf/blob/efa306fdcbe605ec6d17f4cf72c707f7227af52a/src/cmd/common/viper.go#L164) function doesn't accept any parameters and doesn't seem to have access to anything that would tell it what …
> chore: only show config file if there is one

- src/pkg/cluster/state.go
- src/pkg/cluster/zarf.go
- src/pkg/cluster/zarf_test.go
- src/pkg/interactive/components.go
- src/pkg/interactive/prompt.go
- src/pkg/layout/component.go
- src/pkg/layout/package.go
- src/pkg/layout/sbom.go
- src/pkg/lint/validate.go
- src/pkg/message/pausable.go
- src/pkg/transform/image.go
- src/pkg/utils/bytes.go
- src/pkg/utils/bytes_test.go
- src/pkg/utils/cosign.go
- src/pkg/utils/network.go
- src/pkg/variables/variables.go
- src/pkg/variables/variables_test.go
- src/pkg/zoci/fetch.go
- src/pkg/zoci/pull.go
This PR is intended to remove unnecessary named returns and clean up/refactor some nearby functions. Substantial refactors should also be accompanied by tests. This intentionally ignores packager directories to avoid too much churn alongside packager refactoring.
Run `golangci-lint run --disable-all -E nonamedreturns --exclude-dirs='packager' ./src/pkg/...` prior to these fixes to see the intended scope of fixes here. The remaining items outside of pkg #2950 will be fully addressed in another PR. This one was starting to sprawl.
Partially fixes #2950
> refactor: trim named returns in pkg #2950

- src/internal/agent/hooks/argocd-application.go
- src/internal/agent/hooks/argocd-repository.go
- src/internal/agent/hooks/flux-gitrepo.go
- src/test/e2e/28_wait_test.go
Continuation of #2979 which finishes the issue. I was intending to keep smaller PRs limited by component, but it turns out the last PR was about 95% of the needed changes. This one's pretty small with an even smaller blast radius.
Fixes #2950
> chore: finish removing named returns outside of package and extensions #2950

- src/cmd/tools/helm/load_plugins.go
- src/pkg/cluster/pvc.go
- src/pkg/cluster/tunnel.go
- src/pkg/cluster/zarf.go
- src/pkg/transform/artifact.go
- src/pkg/utils/io.go
- src/pkg/utils/yaml.go
- src/pkg/zoci/pull.go
This PR goes through everything in src (ignoring packager and extensions)  and ensures we don't return an error as well as some kind of partial or dirty state from our return vars. Most of these weren't actual vectors for bugs or system instability, it's just good practice. There's some minor cleanups along the way too. 
It's worth noting that I used a specific ag command to find error returns (discussed in #2951) so any error variables not starting with `err` will have been missed in this refactor. I expect that there will be very few of these given how err is the convention.
I left some review notes which I'll highlight in comments for whoever gets eyes on.
Fixes #2951
> chore: ensure we return zeroed value when returning errors

- .github/workflows/scan-codeql.yml
- .github/workflows/test-shim.yml
matrix jobs add to the job name which breaks the shim. Additionally, codeql can break during merge queues so we are going to stop running it in merge queues for the time being. It should be impossible for a change from a previous branch to cause a new security error in the merged branch anyway. 
Fixes #2954
> ci: stop codeql on merge queue

- site/src/content/docs/commands/zarf_package_deploy.md
- site/src/content/docs/commands/zarf_package_pull.md
- src/cmd/package.go
- src/config/lang/english.go
- src/test/e2e/00_use_cli_test.go
Currently the `zarf package pull <https-url>` has no shasum flag, since we recently removed the insecure functionality in #2936 this means it's impossible to pull a package with an https url on main. This PR adds the shasum flag as well as a test.
Fixes #2999
> fix: add shasum flag and test for https pull

- src/cmd/dev.go
- src/pkg/lint/lint.go
- src/pkg/lint/lint_test.go
- src/pkg/lint/schema.go
> refactor: lint

- .gitattributes
This change adds configuration to .gitattributes that was previously removed.
> fix: gittributes to ignore image file endings

- src/cmd/package.go
- src/internal/packager2/load.go
- src/internal/packager2/load_test.go
- src/internal/packager2/remove.go
- src/pkg/cluster/zarf.go
- src/test/e2e/25_helm_test.go
> refactor: remove

- src/pkg/cluster/zarf.go
Discussed on slack, tl;dr is: currently no matter what `PackageSecretNeedsWait` method returns we just return the package, we need to invert the condition to wait, ie. return an error, to give the `retry.DoWithData` to do its job. 
None
> fix: modify the wait condition according to return values from earlier method call

- src/test/nightly/ecr_publish_test.go
fixes #3032 
We could `os.Stat` the file, but then we'd have to parse by `tmpDir/fileprefix` and I'm unsure if that is really beneficial over "checking log output" 🤷🏻‍♀️
> fix: nightly by removing logline no longer printed

- src/internal/packager/helm/chart.go
Helm has an easy way to pass context through during install and upgrade.  We've since started passing context throughout Zarf, now that it's available in these functions we should pass it through
Relates to #2647
> feat: pass context to helm install & upgrade

- src/test/nightly/ecr_publish_test.go
`Packager2`'s Load function doesn't output these anymore. 
I was running my brew installed Zarf binary to test which is from like 2022, rebuilt locally confirmed. 🙃
> fix: nightly ecr test

- src/internal/packager/images/common.go
- src/internal/packager/images/push.go
- src/internal/packager2/mirror.go
Removing the progressbar on image push as we believe that it is causing Zarf to drop the connection to the registry on large image pushes.
Relates to #2864 #2104
> feat: remove progressbar on image push

- .github/actions/cleanup-files/action.yaml
- Makefile
The package delete logic removes more than it should. This change removes it from the clean action to fix the release process.
> Fix release by removing package delete

- src/test/e2e/10_component_flavor_test.go
This change removes any use of CLI output for flavor e2e tests. This enables the refactoring of log output without breaking the e2e tests.
> Refactor flavor e2e test to not depend on CLI output

- src/test/e2e/06_create_sbom_test.go
This change removes any use of CLI output for sbom e2e tests. This enables the refactoring of log output without breaking the e2e tests.
> Refactor sbom e2e test to not depend on CLI output

- src/test/common.go
- src/test/e2e/03_deprecations_test.go
- src/test/e2e/main_test.go
This change removes any use of CLI output for deprecated e2e tests. This enables the refactoring of log output without breaking the e2e tests.
> Refactor deprecation e2e test to not depend on CLI output

- src/test/e2e/04_create_templating_test.go
- src/test/packages/04-file-folders-templating-sbom/zarf.yaml
This change removes any use of CLI output for templating e2e tests. This enables the refactoring of log output without breaking the e2e tests.
> Refactor templating e2e test to not depend on CLI output

- .golangci.yaml
- go.mod
- go.sum
- src/cmd/package.go
- src/cmd/root.go
- src/cmd/tools/zarf.go
- src/config/lang/english.go
- src/internal/packager/helm/repo.go
- src/internal/packager/images/pull.go
- src/internal/packager/sbom/catalog.go
- src/internal/packager/template/template.go
- src/pkg/layout/component.go
- src/pkg/layout/package.go
- src/pkg/logger/logger.go
- src/pkg/packager/actions/actions.go
- src/pkg/packager/common.go
- src/pkg/packager/create.go
- src/pkg/packager/creator/normal.go
- src/pkg/packager/creator/skeleton.go
- src/pkg/utils/network.go
- src/types/packager.go
This PR:
- Adds contributor QOL improvements:
- `sloglint`
-  New formats: `devslog` (via `--log-format="dev"`) and `console-slog` (via `--log-format="console"`)  
- adds WithContext to `packager.Packager` and stores a context on it so we can log in its New() which has some load bearing logging. This is intended as a workaround.
- Makes an empty log format, the default, `--log-format=""`  == "none. So slog must be directly enabled.
- Adds setup functions for both message and logger in `cmd/root` and feature flagging for disabling message and using logger.
- When a log-format is provided, `setupMessage()` ensures PTerm output is discarded and sets the values for `--no-progress`, and `--confirm`.
- Adds structured logging outputs throughout `zarf package create`
- Marks TODOS on message …
> feat: migrate package create to slog

- src/internal/packager/images/pull.go
@AustinAbro321 suggested this improvement to the image pull logging while we reviewed #3132. This gives users better feedback into the parts of pull that we expect will take a while. Also added durations to the debug "done" logs so we get a bit more perf data.
Relates to #3132
> chore: improve the Info and Debug logging for image pulls

- src/internal/packager2/remove.go
> chore: add logger to packager2 Remove

- src/cmd/package.go
- src/internal/packager/sbom/tools.go
- src/internal/packager2/inspect.go
- src/pkg/packager/creator/normal.go
- src/pkg/packager/inspect.go
> chore: add logger to packager2 inspect

- src/cmd/package.go
- src/pkg/cluster/cluster.go
Does what it says on the tin. This keeps message around for table rendering but we may remove that before release for something better.
> chore: add logger to packager2 list

- src/cmd/root.go
- src/internal/packager/images/pull.go
- src/internal/packager/template/template.go
- src/pkg/logger/logger.go
- src/pkg/logger/logger_test.go
When a library takes in a logger we currently have a way for it to respect the logging feature flag as we move to slog. This PR adds functionality to enable that
> chore: feature flag to enable switching between logger for libaries

- src/internal/packager2/mirror.go
- src/pkg/cluster/tunnel.go
> chore: add logger to packager2 Mirror

- src/cmd/destroy.go
- src/internal/packager/helm/chart.go
- src/internal/packager/helm/destroy.go
- src/pkg/cluster/cluster.go
- src/pkg/cluster/namespace.go
- src/pkg/cluster/state.go
- src/pkg/cluster/zarf.go
- src/pkg/packager/remove.go
Adds logger to `zarf destroy` and the code paths it depends on. As a side note, this cmd is very much in need a refactor and de-nesting. 
> chore: add logger to zarf destroy

- src/cmd/dev.go
- src/pkg/packager/prepare.go
- src/pkg/transform/types.go
This PR adds logger to `sha256sum`, `patch-git`, `lint` and `find-images`. There's a few more dev commands to update, which i'll grab in another PR.
> chore: begin adding logger to `zarf dev`

- src/api/v1alpha1/component.go
- src/internal/packager/helm/chart.go
- zarf.schema.json
This introduces the `SchemaValidation` in the Zarf Helm Chart schema. This is important for the airgap use case. If a helm values schema reaches out to the internet it will break in the airgap
Fixes #3123
Fixes #3118
> feat: expose Helm skip schema validation option in Zarf schema

- src/pkg/logger/logger.go
The team has discussed the default logging experience in depth and arrived at using console-slog as the intended default "text" handler. No color for now though, but maybe in the future. (delete "console" if we add color to text)
> feat: use console-slogger as text handler

- src/test/e2e/29_config_file_test.go
This change removes any use of CLI output for config e2e tests. This enables the refactoring of log output without breaking the e2e tests.
> Refactor config e2e test to not depend on CLI output

- .github/workflows/nightly-ecr.yml
- .github/workflows/nightly-eks.yml
Since individual forks are unlikely to have all of the secrets necessary for running these two jobs, it would probably make sense to only limit them to be run in the `zarf-dev/zarf` repository.
Fixes #
Relates to #
> chore: make the nightly tests run only in `zarf-dev/zarf`

- src/pkg/packager/generate.go
> chore: slogger for zarf dev generate

- src/internal/packager2/layout/oci.go
- src/internal/packager2/layout/oci_test.go
- src/internal/packager2/layout/package.go
- src/internal/packager2/layout/package_test.go
This implements a new push function that supports the new package layout. 
Relates to #3181 
Relates to #3180
> Refactor zoci push to support new package layout

- src/internal/packager/template/template.go
- src/internal/packager/template/template_test.go
- src/pkg/packager/creator/normal.go
We were manually putting together a json, refactored this to edit the object then marshall/log the json direct
> refactor: debug template print

- packages/distros/k3s/zarf.yaml
- src/test/e2e/20_zarf_init_test.go
This upgrades to use K3S 1.29, which is a strict requirement of Big Bang >= 2.39.0
N/A
> Upgrading to k8s v1.29 for distro k3s package

- src/cmd/common/viper.go
- src/cmd/root.go
When we have a config file error that isn't not found we shouldn't ignore it
Fixes #3192
> feat: exit on config file error

- src/cmd/connect.go
- src/pkg/packager/prepare.go
This implements slog for connect
> feat: implement new logger for Zarf connect

- src/pkg/logger/logger.go
Fix some comments that weren't updated when logger From was simplified and shuffle some impl. details around for readability, flow, vibes etc.
> chore: true up logger comments and minor refactors

- .pre-commit-config.yaml
- src/internal/gitea/gitea.go
- src/pkg/cluster/injector_test.go
- src/pkg/message/credentials.go
- src/test/e2e/03_deprecations_test.go
- src/test/e2e/08_create_differential_test.go
- src/test/e2e/22_git_and_gitops_test.go
This updates the code to fix some new lint errors that appeared. Also updates the version of https://github.com/pre-commit/pre-commit-hooks as that was giving a warning
> chore: fix lint

- site/src/content/docs/ref/actions.mdx
While reading the `actions` docs I noticed this typo of a double-quote in "it's".
> fix(docs): replace `it"s` with `it is`

- Dockerfile
- packages/zarf-agent/manifests/deployment.yaml
Fixes: #3244
This PR now sets stricter file permissions on the Zarf executable as well, this way if the permissions are changed in the future, it is tested.
> fix: change agent to run as same user in dockerfile

- src/internal/packager/helm/chart.go
- src/test/e2e/25_helm_test.go
- src/test/packages/25-helm-release-history/chart/Chart.yaml
- src/test/packages/25-helm-release-history/chart/templates/configmap.yaml
- src/test/packages/25-helm-release-history/zarf.yaml
This change limits the Helm history secrets to 5 in an attempt to stop massive amounts of secrets to be created over a long time.
Fixes #3242
> Set Helm max history to limit secret creation

- src/pkg/packager/publish.go
- src/test/e2e/50_oci_publish_deploy_test.go
This one ended up being really simple because most of the downstream code had already been ported to slog. I started updating the tests to use the new logging, but decided that it's better if we wait until we swap over to the default format. Added a couple review comments for discussion.
> feat: add logger to packager.Publish

- .github/dependabot.yaml
This change groups k8s dependency updates into a single PR to make merging updates faster and easier.
N/A
> Group k8s dependabot dependency updates

- src/internal/packager2/layout/create.go
- src/internal/packager2/layout/deprecated.go
- src/internal/packager2/layout/deprecated_test.go
- src/internal/packager2/layout/layout.go
This change refactors the deprecation migration and adds unit tests.
> Refactor migrate deprecated

- src/internal/packager2/layout/create.go
In #3169 we allowed Zarf init packages to be explicitly versioned rather than always being the binary version. This behavior was not brought over to packager2
> feat: allow init packages to be explicitly versioned

- site/src/content/docs/commands/zarf_dev_find-images.md
- src/cmd/dev.go
- src/cmd/tools/zarf.go
This removes the deprecated get git password command which has been deprecated for over a year. It was replaced by `zarf tools get-creds git`. This command was already broken because when the get-creds command was updated to use the `RunE` function, `get-git-password` was not updated so it panic'd
> chore: remove deprecated get git password command

- site/src/content/docs/ref/init-package.mdx
This documents the crc32 hash that is appened to images which we frequently get asked about in the Zarf k8s slack
> docs: image crc32 hash mutation 

- site/src/content/docs/faq.mdx
Small fix to the docs to update the API Version in the examples.
N/A
> Fix API Version for Flux resource in docs

- src/cmd/dev.go
- src/cmd/initialize.go
- src/cmd/package.go
- src/pkg/packager/common.go
- src/types/packager.go
There is currently a small bug in the when using the `--log-format` flag that causes not all logs to be seen as context is not passed properly into the packager struct. 
Passing context into structs is not ideal, this was done to avoid breaking changes. The packager struct will be removed once #2969 is completed
> fix: passing context into packager

- src/api/v1alpha1/package.go
- src/internal/packager2/layout/oci.go
- src/internal/packager2/layout/oci_test.go
- src/pkg/zoci/push.go
- zarf.schema.json
Adds metadata annotations
Fixes #2976
> feat: add metadata.annotations to package schema

- src/pkg/logger/logger.go
- src/pkg/packager/create.go
- src/pkg/packager/deploy.go
- src/pkg/packager/interactive.go
I realized many warnings before confirm actions weren't being printed. We were printing some of the pre-confirm warnings separately which leads to cleaner code, however practically speaking they are almost impossible to notice for users because everything before the `p.confirmAction` happens quickly and `p.confirmAction` prints out a yaml file.
> feat: print warnings before confirm with slogger

- src/cmd/connect.go
- src/cmd/destroy.go
- src/cmd/dev.go
- src/cmd/initialize.go
- src/cmd/internal.go
- src/cmd/package.go
- src/cmd/root.go
This refactor is a first step to isolating all the command, which should allow easier consumption of zarf in other places. 
Relates to #2773
> refactor: Create structs for each command to  better isolate commands

- src/cmd/common/viper.go
- src/cmd/initialize.go
- src/cmd/package.go
- src/cmd/root.go
- src/cmd/tools/archiver.go
- src/cmd/tools/common.go
- src/cmd/tools/crane.go
- src/cmd/tools/helm.go
- src/cmd/tools/k9s.go
- src/cmd/tools/kubectl.go
- src/cmd/tools/syft.go
- src/cmd/tools/wait.go
- src/cmd/tools/yq.go
- src/cmd/tools/zarf.go
Continuation of the effort to isolate commands. Followup to #3322.
This PR additionally changes how viper is initiated, see the first commit for that specifically. 
Relates to #2773
> refactor: Create structs for each tools command to better isolate commands - cont'd 

- site/src/content/docs/commands/zarf_package_create.md
- site/src/content/docs/commands/zarf_package_publish.md
- src/cmd/package.go
- src/config/lang/english.go
> fix: allow non-interactive package publish with signing key

- .github/workflows/nightly-ecr.yml
- site/src/content/docs/commands/zarf_package_pull.md
- src/cmd/package.go
- src/internal/packager2/pull.go
- src/internal/packager2/pull_test.go
- src/test/e2e/11_oci_pull_inspect_test.go
- src/test/nightly/ecr_publish_test.go
During #3348 we added the requirement to use the `--key` flag for signed packages during `zarf package pull`. This broke a nightly test . Additionally, we did not add the `--skip-signature-validation` flag in #3348 which should have been added
Relates to #3346 
Manually run workflow showing it's fixed - https://github.com/zarf-dev/zarf/actions/runs/12416094320
> fix: include key in nightly e2e pull from ecr test

- .github/dependabot.yaml
These tend to release around the same time and cause a lot of dependabot PRs / dependabot rebasing
> chore: group cosign providers dependabot updates

- .github/actions/stale/actions.yml
Reason:
As a smaller open source team it can be difficult without set triage people to manage the inbound requests. To keep ontop of the amount of requests I propose we start to mark issues stale after 60 days. After 70 days of no activity the issue will be closed.
Pull requests will never be closed, but marked stale after 45 days.
If an issue or PR is assigned to a milestone it will exempt from this.
> chore: add stalebot

- src/internal/packager2/layout/create.go
- src/internal/packager2/layout/import.go
- src/internal/packager2/layout/import_test.go
- src/internal/packager2/layout/testdata/import/first/zarf.yaml
- src/internal/packager2/layout/testdata/import/second/zarf.yaml
- src/internal/packager2/layout/testdata/import/third/zarf.yaml
This change adds import chains to the packager2 which were never implemented during the refactor.
Relates to #3180
> Add support for import chains in packager2

- src/cmd/package.go
- src/internal/packager2/inspect.go
In #2990 we changed the `zarf package inspect --list-images` logic to print both the image list and the color printed yaml file. This reverts back to the old behavior of only printing the image list, which should make it easier for users to view / parse this list. 
Fixes #3374
> fix: print image list without package yaml when using `--image-list` flag with inspect

- .github/dependabot.yaml
This adds hack/schema to the dependabot directory so dependabot will update both directories when both need to be updated, such as in #3378
ref: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--
> chore: multi directory gomod dependabot

- src/internal/packager/images/pull.go
- src/internal/packager/images/pull_test.go
- src/internal/packager/images/testdata/invalid-cache-layer/sha256:94c7366c1c3058fbc60a5ea04b6d13199a592a67939a043c41c051c4bfcd117a
Zarf was not properly deleting invalid layers during image pull
Relates to #3194 - pretty sure this will fix it, but I will give it some time to see if the flake disappears
> fix: properly delete invalid layers during image pull

- src/config/config.go
> fix: avoid erroring when $HOME is not defined

- src/cmd/dev.go
- src/test/e2e/00_use_cli_test.go
Fixes a bug where user variables were not getting transformed to uppercase.
> fix: transform set variables to uppercase in dev inspect definition

- Makefile
- src/internal/packager/sbom/catalog.go
- src/test/external/common.go
There is a flake we often get in test external #3194 relating to a broken Zarf cache. Likely, this will not get resolved until we either stop pulling packages in parallel (unlikely as it would make pulling signifigantly slower), or move away from crane (planned but will take time). Adding this in as a band aid to avoid flakes
> test: avoid flake in test external

- .github/release.yml
The current release notes are hard to read because so much of it is dependabot updates. By separating it out, it will be easier to parse. Tried it out to make sure it works as I expected - https://github.com/AustinAbro321/goreleaser-test/releases
> chore: separate code changes from dependency updates in release notes

- .github/dependabot.yaml
Golang often releases their changes together. Generally they work with one another and often update the same dependencies so this avoids the double review and merge conflict errors
> chore(deps): group golang dependencies in dependabot

- src/test/e2e/10_component_flavor_test.go
This deletes the e2e test for package flavors. The other test in [10_component_flavor_test.go](https://github.com/zarf-dev/zarf/blob/33d8a2a2dc84b89913cc74d45157a04f6230c5ec/src/test/e2e/10_component_flavor_test.go#L37) already covers flavors and `layout2.LoadFromTar` more in depth. We have unit tests for verifying package builds with flavors as well. 
I think the package-flavors example does a good job of showing off the `--flavor` feature, but doesn't make for a good e2e test. Especially since it pulls images from dockerhub which can lead to flakes on TOOMANYREQUESTS.
> test: delete e2e test for examples/package-flavors

- src/internal/packager/helm/repo.go
Rather than use [`FindChartInAuthRepoURL`](https://github.com/helm/helm/blob/301108edc7ac2a8ba79e4ebf5701b0b6ce6a31e4/pkg/repo/chartrepo.go#L208), we can instead use [`FindChartInAuthAndTLSRepoURL`](https://github.com/helm/helm/blob/301108edc7ac2a8ba79e4ebf5701b0b6ce6a31e4/pkg/repo/chartrepo.go#L216) and pass  the Zarf CLI `--insecure-skip-tls-verify` boolean flag down directly via `config.CommonOptions.InsecureSkipTLSVerify`.
Fixes #3476
> fix: pass insecure flag option to FindChartInAuthAndTLSRepoURL

- site/src/content/docs/faq.mdx
- src/pkg/packager/publish.go
We've heard complaints about skeleton packages being confusing, I expect them to be deprecated and their use case along custom init packages to be replaced some day, but for now I wanted to make it more clear to users that they are publishing a skeleton package and what that means.
> feat: improve skeleton package messaging

- .github/workflows/build-rust-injector.yml
We reworked the injector process to use cross, but didn't install cross before building
> chore(release): install cross before injector build

- src/internal/packager2/pull.go
Previously, Pull would only report errors to users by passing nested errors up the chain from ORAS. This focused more on internal library details than actionable user behavior. This PR is a first pass at adding debugging context with metadata and some info, error, and debug logs to packager2.Pull.
> feat: add more logging to packager2.Pull

- src/internal/packager2/load_test.go
- src/pkg/cluster/zarf.go
- src/pkg/packager/deploy.go
- src/test/e2e/37_component_status_test.go
- src/test/packages/22-git-data/zarf.yaml
- src/test/packages/37-component-status/component-status.yaml
- src/test/packages/37-component-status/zarf.yaml
- src/types/k8s.go
Adds back in deployed component status when deploying a package. 
...
Fixes #3553
> feat: recording deployed component status in package deploy

- src/internal/git/repository_test.go
Current test logic is coupled with the hosts ~/.gitconfig. If the host has 
```
[init]
defaultBranch = main
```
Then the `TestRepository` unit test at `src/internal/git/repository_test.go` will fail. 
Undetermined how to decouple this fully within `go-git` as of yet. Issues are unclear and mixed results as far as consuming `$HOME/.gitconfig` are concerned and all explicit definition of `main` for `defaultBranch` still results in the `HEAD` containing the hosts default branch and not the configuration. 
This change re-writes the `HEAD` file to match the explicit `InitOptions` such that it will now pass when the hosts `.gitconfig` does not align to the original workflow. 
Fixes #3567
> fix(unit): resolve TestRepository host git configuration dependency

- .github/workflows/publish-application-packages.yml
- .github/workflows/test-upgrade.yml
The setup-zarf action was moved from the defense unicorns organization to zarf-dev
> chore: use setup-zarf from zarf-dev 

- src/test/external/ext_in_cluster_test.go
I noticed this flake here, seemingly because it took too long. https://github.com/zarf-dev/zarf/actions/runs/14092394407/job/39472052129
> test: increase timeout for in cluster test health check

- src/internal/packager2/layout/import.go
- src/internal/packager2/layout/import_test.go
- src/internal/packager2/layout/testdata/import/flavor/child/zarf.yaml
- src/internal/packager2/layout/testdata/import/flavor/expected.yaml
- src/internal/packager2/layout/testdata/import/flavor/zarf.yaml
A bug was introduced in #3597 which caused validation to improperly fail when a flavor is used by a child component but not used by a parent component. It stems from the fact that flavors are not set on the composed component when a child component has one. This PR updates the behavior to set the flavor on the newly composed
> fix: set flavor on composed component

- packages/zarf-registry/zarf.yaml
> fix: init-package s3 url

- src/internal/packager2/layout/create.go
- src/internal/packager2/layout/create_test.go
- src/internal/packager2/layout/import.go
This PR adds some debug logging and the package name to resolving and validating imports. We also append the package name to a flavor validation error - the error message is otherwise unchanged.
Before:
After:
#3597
> feat!: Add debug granularity to package create validation and update error message

- site/src/content/docs/commands/zarf_init.md
- site/src/content/docs/commands/zarf_package.md
- site/src/content/docs/commands/zarf_package_create.md
- site/src/content/docs/commands/zarf_package_deploy.md
- site/src/content/docs/commands/zarf_package_inspect.md
- site/src/content/docs/commands/zarf_package_inspect_definition.md
- site/src/content/docs/commands/zarf_package_inspect_images.md
- site/src/content/docs/commands/zarf_package_inspect_sbom.md
- site/src/content/docs/commands/zarf_package_list.md
- site/src/content/docs/commands/zarf_package_mirror-resources.md
- site/src/content/docs/commands/zarf_package_publish.md
- site/src/content/docs/commands/zarf_package_pull.md
- site/src/content/docs/commands/zarf_package_remove.md
- src/cmd/initialize.go
- src/config/lang/english.go
- src/internal/packager2/layout/import.go
As a part of #3559 the oci-concurrency flag was made to work with container images, however the language was not changed to reflect this and it was never added to `zarf init`.
> fix: oci-concurrency flag on init

- src/pkg/packager/prepare.go
add pod, cronjob, and replicationcontroller to minimize usage of standard submatching
This pull request does not add any features or changes any code flow.
The `processUnstructuredImages()` function iterates over resources and passes child PodSpec resources into `appendToImageMap()` to grab a list of all required images. 
While following logic, thought it would be more cohesive to support **all** resources that include Pod specs, include Pod itself, CronJob and ReplicationController (although legacy).
...
Not related to any existing issues.
> refactor: include all workload resources

- src/internal/packager2/layout/create.go
- src/internal/packager2/layout/create_test.go
- src/internal/packager2/layout/testdata/zarf-skeleton-package/zarf.yaml
Attempting to create a component using `manifests.kustomizations` without any `manifests.files` will fail because it silently relies on the manifests.files loop to create the parent directory `manifests` which `kustomize.Build()` expects to exist in order to write the file. 
Updated the `create_test.go` to include a component which has kustomizations in isolation in order to detect this going forward. 
Fixes #3667
> fix(skeleton): resolve support for kustomizations in isolation

- src/api/internal/v1beta1/component.go
- src/api/internal/v1beta1/package.go
- src/api/internal/v1beta1/package_test.go
- src/api/internal/v1beta1/translate.go
- src/api/internal/v1beta1/translate_test.go
We have had users confused on why v1beta1 doesn't work with the rest of Zarf. V1beta1 is work in progress. This PR moves it to an internal package to avoid confusion. 
Relates to #3433
> chore: move v1beta1 internal

- src/cmd/crane.go
Looks like Crane has a bug in their validation - https://github.com/google/go-containerregistry/pull/2088
Fixes #3644
> fix: require username and password for `zarf tools registry login`

- src/internal/packager2/layout/create.go
- src/internal/packager2/layout/create_test.go
In #3597 I added validation for flavors, however I did not anticipate that users intentionally created packages with unused flavors to set different tags on the package. As we don't have an alternative at the moment, this PR allows unused flavors again, but with a warning
> feat: allow unused flavors with a warning

- src/internal/packager2/layout/create.go
- src/internal/packager2/layout/create_test.go
In #3683 I implemented flavors with a warning if a flavor is not used. However there was a mistake in the logic so it warns even when flavor aren't used
> fix: stop warning users when flavors are not used

- src/internal/packager2/layout/import.go
- src/internal/packager2/layout/import_test.go
- src/internal/packager2/layout/testdata/import/variables/expected.yaml
- src/internal/packager2/layout/testdata/import/variables/import/zarf.yaml
- src/internal/packager2/layout/testdata/import/variables/secondImport/zarf.yaml
- src/internal/packager2/layout/testdata/import/variables/zarf.yaml
There is a bug in compose that causes duplicates variables to appear. `slices.CompatFunc` was used to de-duplicate variables, however since it only compares consecutive elements there were a lot of opportunities for misses. 
Fixes #3707
> fix: ensure variable uniqueness during compose

- src/pkg/cluster/tunnel.go
This updates the tunnel package to use the Kubernetes portforward websocket feature. This should resolve long standing issues in the community that makes Zarf incompatible with tools like aws ssm as the current port forward method does not work well with proxies or gateways. 
Fixes #3715
> feat: use websockets for port forwards

- src/internal/packager/images/push.go
- src/internal/packager2/mirror.go
In #3559 we moved from Crane to ORAS. As part of that move, the retry logic was removed on image push.  ORAS does have builtin retries but these do not account for failures on the port-forward. For example, an HPA may spin down the Zarf registry and break, these situations can only be saved by retrying and creating another tunnel. By adding back in retries at the Zarf level, we can account for these situations. 
To manually test a pod failure, I restarted the Zarf registry mid push. I verified that I got a failure doing this on current Zarf, and verified that this will recover when trying with the change in this PR
> feat: add retries to image push

- src/cmd/package.go
- src/internal/packager/images/common.go
- src/internal/packager/images/pull.go
- src/internal/packager/images/push.go
- src/internal/packager2/layout/create.go
- src/internal/packager2/mirror.go
- src/pkg/packager/creator/normal.go
- src/pkg/packager/deploy.go
Fix support for images.Pull/Push honoring the `--insecure-skip-tls-verify` flag. 
Fixes #3724
Relates to #
> fix(images): support for insecure skip tls verify on image push/pull

- src/internal/packager2/pull.go
Agree with below issue that the empty digest log can be confusing. I could have added to the log with conditionals, but given that the shasum is strictly user input and is more traditionally given on oci objects with the `@sha256:..` format I believe it's simpler to remove. 
For example a user could run
```bash
starting pull from oci source src=oci://ghcr.io/austinabro321/helm-charts:0.0.1@sha256:bce489695b38ac0e6c3660c8fbc8498aee9d2180db9887d62d79fd3c7508e00c digest=
```
They are using a digest in this situation, but since it's on the OCI object it looks like it's empty.
I kept the log on `http(s)` pulls as the digest is required 
Fixes #3622
> feat: remove user submitted digest from OCI pull log

- go.mod
- go.sum
- hack/schema/create-zarf-schema.sh
- hack/schema/go.mod
- src/api/internal/v1beta1/component.go
- src/api/v1alpha1/component.go
- src/internal/packager2/layout/import.go
- src/internal/packager2/layout/import_test.go
- src/pkg/lint/schema_test.go
- zarf.schema.json
In #2886 the json schema was separated in another directory under hack. However the main zarf go.mod still contained the jsonschema dependency because it was implementing one of the methods to add extra items to the schema outside of what was possible with json/jsonschema tags. 
This was originally added to the schema so users would know that package templates for imports don't work, however since compose runs before the schema checks these schema checks were not reached. By adding explicit validation we can remove the jsonschema dependency and make the error message show up in the relevant workflows.
> chore: remove invopop/jsonschema dependency from root go.mod

- src/test/common.go
- src/test/e2e/00_use_cli_test.go
- src/test/packages/00-archive-path/zarf.yaml
- src/test/packages/00-extract-path/zarf.yaml
Cuts down `TestUseCLI/zarf_package_to_test_archive_path` from 60s to 3s by not using the eks distro package (100Mb) as the test package. Instead a test package is created with similarly structured data. The eks distro package is still built and deployed in nightly.
> test: improve archive test

- src/test/e2e/00_use_cli_test.go
- src/test/packages/00-http-pull/zarf.yaml
Cuts execution time of the pull HTTP test (10s -> 3s on local machine). Removes reliance upon GitHub release artifact and reduces local IO usage. Re-architects test to be more ready to be transitioned to a proper unit test.
> test: improve http pull test

- src/types/k8s.go
There is a bug right now when a user runs `zarf package deploy <init-package>` it won't set the default push user or git repository. I believe this was introduced when cmd was refactored to not use `init()`s at startup. The `init()` seemed to be changing state for `zarf init`, but this behavior was also required by `zarf package deploy`. Regardless, it makes more sense for these default functions to not know what Zarf sets to defaults at the cmd level.
> fix: set default user for git and registry state during `zarf package deploy`

- site/src/content/docs/commands/zarf_package_mirror-resources.md
- src/cmd/package.go
- src/internal/packager2/mirror.go
- src/test/e2e/39_crane_to_oras_test.go
Support for falling-back to zarf state when using `zarf package mirror-resources` without supplying URL flags otherwise returning an error that is clear.
Fixes #2389
> feat(mirror-resources): support for State fallback without flags

- site/src/content/docs/commands/zarf_tools_wait-for.md
- src/cmd/vendor.go
- src/pkg/utils/wait.go
Given an invalid kubeconfig or no connectivity to a cluster - zarf will still wait the full timeout period before exiting - giving the user a false sense of waiting for the resources in some scenarios.
Update:
Proposed changes include removing `wait-for` from the vendored commands list - enabling logging and all other persistentprerun logic. 
Logs were converted to `Info` to enable surfacing to users by default. We are now checking for cluster connectivity explicitly (every 1 second) and logging as such. This continues until the connection is both established and the handoff to the `kubectl wait` command has occurred. 
Example of zarf waiting for a cluster before then waiting for resource state
```bash
dev@dev:~/work/zarf$ ./build/zarf -l debug tools wait-for deploy coredns Available -n …
```
> fix(wait-for): return early on connection refused

- site/src/content/docs/commands/zarf_package_mirror-resources.md
- src/config/lang/english.go
Updates documentation to clarify that `mirror-resources` will use zarf state by default. 
Relates to #3757
> fix(docs): update mirror resources docs to include examples

- src/internal/packager2/actions/actions.go
- src/pkg/utils/wait.go
- src/pkg/utils/wait_test.go
Currently there is a panic when an HTTP server that someone is waiting for returns an error code that is not the expected error code. This is because it will try to call the `.Error()` function on a nil err.
> fix: avoid panic during wait-for HTTP server

- src/cmd/initialize.go
- src/cmd/zarf_tools.go
- src/pkg/packager/sources/oci.go
- src/pkg/zoci/pull.go
`zarf init` and `zarf tools download-init` currently fail because they utilize `packager.sources.Collect()` methods which did not pass the explicit layers required.
This PR updates `init` and `tools download-init` to use `packager2.Pull()` - Adds an early exit error for quick identification - and fixes the problem in `packager1.source.Collect()` to always pull all layers in the event there is another area impacted by this change.
> fix(CLI): migrate to Packager2 for init package downloads

- src/internal/packager2/layout/package.go
- src/pkg/archive/archive.go
- src/pkg/packager/sources/tarball.go
Zarf users of v0.55.2 are experiencing long package load times - impacting those loading large zarf packages. 
The root of the problem is the use of the virtual filesystem in the package load where all files are being loaded into the temporary directory. The random access semantics are great for situations where we need file lookup - but for unarchiving the entirety of a package this can be significantly slower than a sequential stream. 
Examples using `examples/longhorn`
This Branch:
```
real    0m2.499s
user    0m1.407s
sys     0m1.139s
```
Main:
```
real    1m3.592s
user    1m12.046s
sys     0m15.594s
```
This Branch:
```
real    0m4.133s
user    0m1.532s
sys     0m1.256s
```
Main:
```
real    1m4.817s
user    1m12.564s
sys     0m15.392s
```
Fixes #3830
> fix(archive): replace virtualfilesystem with sequential streaming

- src/pkg/archive/archive.go
We have a reproducible example of a component archive `component.tar` being misidentified as having the `brotli` compression and thus failing package deploy and tools archiver decompress due to having an invalid tar header.
This relates to: https://github.com/mholt/archives/issues/29 
Because the raw Brotli format lacks a fixed magic number, decoding 16 bytes of almost any non-Brotli data (including a plain .tar file) often succeeds without error. Meanwhile, the library’s TAR header detector can fail on non-USTAR archives (e.g. V7-style tarballs that don’t include the “ustar” signature), so the only positive match is from the Brotli stream test. The net result: a .tar file is misidentified as Brotli, passed to the Brotli decoder (which outputs junk), and then fed to the Tar …
> fix(archive): skip format autodetection for tar format

- src/cmd/package.go
Does not resolve #3837 but is attributed to the problem where we did not check for the cluster object to be nil before attempting to call the `LoadState` method. 
Relates to #3837
> fix(mirror-resources): add cluster nil check before loading state

- .github/workflows/release.yml
This change removes grype and the cve-report generation from the release workflow. Future iteration will be to align CVE scanning and reporting with developer operations and enable consumers to get more accurate scanning results by improving the recommendation and documentation. 
Fixes #3839
> fix(release): remove grype cve report from release

- src/pkg/utils/wait.go
Previously, `zarf tools wait-for` would require two ctrl-c's from a user to interrupt the process. This PR adds a `ctx.Done()` to `utils.ExecuteWait`'s select and some extra debugging to help trace #3844.
Relates to #3844
> feat(utils): support user interrupts in utils.ExecuteWait and add debug logging

- src/pkg/utils/wait.go
Follow up to #3846, this PR adds the same hook for user-interrupts in the network protocol loop as in the main loop of `utils.ExecuteWait`
See:
Relates to #3846, #3844
> feat(utils): add user interrupts to wait-for on network protocols

- .golangci.yaml
- src/internal/packager/helm/chart.go
- src/internal/packager/images/common.go
- src/internal/packager/images/pull.go
- src/internal/packager/images/push.go
src/internal/packager was excluded from lint on the basis that the packages would be replaced in the packager refactor (#3525), however only src/internal/packager/sbom will be replaced. This PR lints the long lived packages that were excluded.
> chore: lint src/internal/packager

- src/internal/packager2/actions/actions_test.go
- src/internal/packager2/inspect.go
- src/internal/packager2/packager2.go
- src/pkg/packager/actions/actions_test.go
packager2 has not been running golint. There will be a follow up PR to address this and fix every lint error, however this error struck me as something that could cause a bug on main, so I'm creating a quick fix now.
> fix: unchecked err when populating variables for deploy

- src/pkg/archive/archive.go
Fixes the sbom tarball identification by fixing the constant to the appropriate target. 
```
|-- checksums.txt
|-- compare.html
|-- components
|   `-- demo-helm-charts
|       |-- charts
|       |   |-- podinfo-git-6.4.0.tgz
|       |   |-- podinfo-local-6.4.0.tgz
|       |   |-- podinfo-oci-6.4.0.tgz
|       |   `-- podinfo-repo-6.4.0.tgz
|       `-- values
|           |-- podinfo-git-6.4.0-0
|           |-- podinfo-local-6.4.0-0
|           |-- podinfo-oci-6.4.0-0
|           `-- podinfo-repo-6.4.0-0
|-- ghcr.io_stefanprodan_podinfo_6.4.0.json
|-- images
|   |-- blobs
|   |   `-- sha256
|   |       |-- 12cba3a8e34081029e840e7ac5454c080835cbc5a7adc1620482e939283a3a49
|   |       |-- 3e84ea487b4c52a3299cf2996f70e7e1721236a0998da33a0e30107108486b3e
|   |       |-- …
```
> fix(archive): sbom directory regression fix

- .golangci.yaml
- src/internal/packager2/layout/assemble.go
- src/internal/packager2/layout/assemble_test.go
- src/internal/packager2/layout/package.go
- src/internal/packager2/load.go
- src/internal/split/split.go
- src/internal/split/split_test.go
- src/pkg/lint/findings.go
- src/test/e2e/05_tarball_test.go
This moves the split file logic into it's own package, and stops the reliance on the types.ZarfPackageSplitData
> refactor: move split file logic to it's own package

- src/cmd/k9s.go
This resolves the issue below by reproducing the silence of klog as k9s does in [main.go](https://github.com/derailed/k9s/blob/master/main.go). 
Fixes #2549 
After: 
Before:
> fix(monitor): mimic k9s init to silence klog errors

- examples/composable-packages/zarf.yaml
- main.go
- src/config/config.go
- src/pkg/utils/io.go
- src/pkg/utils/io_test.go
- src/pkg/utils/network_test.go
Currently if a library user calls `packager.Create` on a package with an action calling `./zarf` like this
```go
actions:
onCreate:
before:
- cmd: ./zarf version
```
The command will re run the go program calling the Zarf SDK. This is because actions will call `GetFinalExecutableCommand` to replace `./zarf`, and instead of replacing it with the zarfCLI it will replace it with whatever the go program running the Zarf SDK is. 
There is already an override for this with the `config.ActionsUseSystemZarf` global, but it is set to false by defualt. This PR updates it to be set to true by default, but set to false main() that way by default it will be true for library users and false for CLI users.
> feat(sdk): intuitive default path when using `./zarf` actions

- src/cmd/package.go
- src/pkg/packager/create.go
- src/pkg/packager/publish.go
- src/pkg/packager/publish_test.go
- src/pkg/utils/io_test.go
- src/pkg/zoci/common.go
- src/pkg/zoci/copier.go
- src/pkg/zoci/pull.go
- src/pkg/zoci/pull_test.go
- src/pkg/zoci/utils.go
Returns the final path after publish. This makes for a more intuitive experience on the SDK side, where you can publish your package, then use the new reference directly.
It bodes well for this PR that the tests consistently get simplified. Most of the time, in test, after we call this function we put together the ref to do more with it anyway.
> feat(sdk): return final package ref after publish

- src/internal/packager/images/push.go
- src/internal/packager/images/push_test.go
We were allowing users to give a path to oras auth that looks like `registry.com/my-namespace`, but when you give anything more than the host to the oras auth client it breaks. 
Fixes #3915
> fix: properly create push auth credentials when registry address includes a repo path 

- src/cmd/helm/repo_update.go
Appending to `repoFailList` from multiple goroutines is not concurrency safe, so let's wrap a `sync.Mutex` around the append.
Fixes #
Relates to #
> chore: wrap mutex around appending to failed repository updates

- src/pkg/packager/create.go
- src/pkg/packager/create_test.go
- src/pkg/packager/layout/assemble.go
- src/pkg/packager/testdata/create/differential/older-version/zarf.yaml
- src/pkg/packager/testdata/create/differential/zarf.yaml
There is a regression which blocks users from making a differential package from an OCI source. 
This does include a breaking change in the SDK for `layout.assemblePackage`. It's possible to keep this backwards compatible, but IMO it makes sense to change the field here given that:
- Callers are much more likely to call `packager2.create` which still accepts a source, than the more granular `layout.assemblePackage`
- It's simple to get the package definition before `layout.assemblePackage` with `packager2.LoadPackage`
Fixes #3960
> fix!: allow creation of differential package from OCI source

- src/pkg/archive/archive.go
- src/pkg/packager/load/import.go
mholt/archives auto detection has been unreliable. Changing the code to instead detect the format using the filename
Fixes #3917
> fix: identify file type using filename instead of mholt/archives auto detection

- src/cmd/package.go
- src/pkg/packager/deploy.go
This change modifies the signature of `packager.Deploy()` to return the `VariableConfig` of the package deployed. 
Fixes #3975
> feat!(deploy): support return of package VariableConfig

- .github/workflows/release.yml
The release workflow has incorrect actions syntax for setting an env variable
> fix(release): correct GitHub environment variable syntax for GoReleaser version

- .goreleaser.yaml
- README.md
- site/src/content/docs/commands/zarf.md
- site/src/content/docs/commands/zarf_completion.md
- site/src/content/docs/commands/zarf_connect.md
- site/src/content/docs/commands/zarf_destroy.md
- site/src/content/docs/commands/zarf_dev.md
- site/src/content/docs/commands/zarf_init.md
- site/src/content/docs/commands/zarf_package.md
- site/src/content/docs/commands/zarf_say.md
- site/src/content/docs/commands/zarf_tools.md
- site/src/content/docs/commands/zarf_version.md
- site/src/content/docs/faq.mdx
- src/config/lang/english.go
This updates Zarf tagline to "The Airgap Native Package Manager for Kubernetes" instead of "DevSecOps for Airgap". This help should help highlight our main use case, and make it easier to search for Zarf.
Also adds to the FAQ that Zarf is not only used for airgap and Kubernetes, but it is often the highest priority.
Upon merge of this PR I will update the about section in GitHub to use this tagline as well.
Fixes #3478
> docs: update Zarfs tagline

- README.md
- site/src/content/docs/contribute/style-guide.mdx
- site/src/content/docs/faq.mdx
- site/src/content/docs/getting-started/understanding.mdx
- site/src/content/docs/index.mdx
This PR is a follow up to #3991 matching the change in "open-source" to "open source" in Zarf's documentation. ADRs are not in scope for this change.
This PR also updates references to Zarf's original creator company to just point to Zarf.
Relates to #3991
> chore(docs): update open-source to open source and clean up style-guide.mdx

- src/pkg/cluster/cluster.go
- src/pkg/cluster/cluster_test.go
- src/pkg/cluster/injector.go
- src/pkg/cluster/injector_test.go
- src/pkg/packager/deploy.go
Fixes #2357 using option 2 in my most recent comment. 
I tested this with k3d by making only two ports available:
```bash
k3d cluster create --k3s-arg "--service-node-port-range=31998-31999@server:0" --k3s-arg="--disable=traefik@server:0"
```
After a try or two you'll something like
```bash
2025-07-18 10:58:59 INF adding archived binary configmaps of registry image to the cluster
2025-07-18 10:59:06 INF injector service NodePort conflicts with registry NodePort, recreating service conflictingPort=31999
2025-07-18 10:59:07 INF injector service NodePort conflicts with registry NodePort, recreating service conflictingPort=31999
2025-07-18 10:59:09 INF deploying component name=zarf-seed-registry
2025-07-18 10:59:09 INF processing Helm chart name=docker-registry version=1.0.0 …
```
> fix: avoid injector and registry randomly landing on same nodeport

- src/cmd/dev.go
- src/pkg/packager/find_images.go
- src/pkg/packager/find_images_test.go
- src/pkg/packager/testdata/find-images/fuzzy-registry-auth/configmap.yml
- src/pkg/packager/testdata/find-images/fuzzy-registry-auth/zarf.yaml
- src/pkg/packager/testdata/find-images/fuzzy-upstream/configmap.yml
- src/pkg/packager/testdata/find-images/fuzzy-upstream/kustomization.yaml
- src/pkg/packager/testdata/find-images/fuzzy-upstream/zarf.yaml
- src/test/testutil/registry.go
Updates logic that when trying to use `zarf dev find-images` a package, it will silently fail if the registry, in this case registry1.dso.mil, needs auth to check it.
Fixes #4007
> feat: add logic to add image to possible list when auth is needed

- src/internal/packager/helm/zarf.go
- src/test/external/ext_out_cluster_test.go
Fix support for subpaths in the use of external registries during `zarf tools update-creds agent`. 
Most managed external registries will not have the root registry available to push images. Rather a organization with nested projects may be defined - such as `registry.example.com/organization`. 
Zarf init for the agent - which is pre-mutation - is set as `registry.example.com/organization/zarf-dev/zarf/agent:<tag>`
In this scenario - the current logic for updating the agent tls certificate was identifying:
registry = `registry.example.com`
path = `organization/zarf-dev/zarf/agent`
and assigning the full path - `organization/zarf-dev/zarf/agent` - to the image - which when the registry is appended now equals `registry.example.com/organization/organization/zarf-dev/zarf/agent:<tag>`.
This …
> fix(tools): update-creds handle registry subpaths

- examples/component-actions/zarf.yaml
- src/pkg/packager/inspect.go
- src/pkg/packager/layout/assemble.go
- src/pkg/packager/layout/layout_test.go
Allows users to use absolute paths again. Also eliminates some duplication between find-images / inspect and assemble
Fixes #3867
> fix: allow absolute paths in zarf.yaml

- src/pkg/packager/create.go
- src/pkg/packager/layout/assemble.go
- src/pkg/packager/layout/layout_test.go
This allows users to use absolute paths in values file with zarf packages
Fixes #3867
> fix: values file absolute path

- go.mod
- go.sum
Resolves vulnerability GHSA-wjrx-6529-hcj3. the use of this dependency originates from Syft and we need to wait for them to release.
Given the timeline to release - doing this now is advantageous. 
No issue
> chore(deps): update go-getter to resolve GHSA-wjrx-6529-hcj3

- src/cmd/package.go
This removes most of the hints from the package yaml. The only one that is kept is the hint that gives the variable values as this hint could be relied on, and it doesn't take up extra newlines. Otherwise, the feedback I've gotten from users is that the hints don't add much value. As we've seen the general user base of Zarf shift towards more automated deploys, keeping there is less of a case for keeping these in. Additionally there is currently a bug with how the hints display variables.
Fixes #2974
> feat: remove hints from deploy yaml print

- .github/dependabot.yaml
This PR adds a list of compromised package versions as as result of a supply chain attack, described here: https://www.aikido.dev/blog/npm-debug-and-chalk-packages-compromised. Zarf was not affected by this attack, and many of the compromised package versions have been removed as of the time of this PR. The CVE has also been flagged and registered, so it's likely that Dependabot already won't generate PRs for versions.
However, out of an abundance of caution, we're intentionally removing these packages from Dependabot updates to ensure we don't pull in a known-bad package.
> fix: update dependabot npm ignores to compromised library versions

- go.mod
- src/pkg/cluster/injector.go
- src/pkg/cluster/injector_test.go
This introduces an additional iteration through node pods in order to get an accurate calculation for available resources. This provides a more accurate representation of resources available on a node - as the injector skips the scheduler - which would normally provide this information. 
Fixes #4218
> fix(injector): improve node resources availability for injector

- site/src/content/docs/getting-started/install.mdx
Brew supports passing in a "fully-qualified" reference to a formula, which automates the `tap` step before installing, making it a single command to run.
I'm not sure how long this has been around, but as best as I can tell this is not new functionality (I want to say I've used this syntax for the past ~2 years or so).
> docs: use fully-qualified brew install command
