examples/tiny-kafka/zarf.yaml
World is happy again. <img width="1207" alt="Screen Shot 2021-09-23 at 3 25 54 PM" src="https://user-images.githubusercontent.com/882485/134578893-fa6bccde-03ae-4b49-ad62-fec689c52f93.png">
Fixes #56
=> Fixes #56. Update kafka tools URL

examples/big-bang/template/bigbang/values.yaml, examples/big-bang/zarf.yaml
- `examples/big-bang/template/bigbang/values.yaml`: Remediate kubescape findings and add a TODO to fix the control plane CIDR
- `examples/big-bang/zarf.yaml`: Add missing image
=> Update Big Bang Core example with `kubescape` remediations

cli/cmd/prepare.go, cli/internal/utils/network.go, cli/internal/utils/shasum.go, e2e.sh
=> Add zarf prepare sha256sum URL arg for remote SHASUM

examples/Makefile, examples/big-bang/README.md, examples/big-bang/files/kubescape-exceptions.json, examples/big-bang/zarf.yaml
* Update examples/big-bang/README.md with a better kubescape command
* Add the WIP kubescape exceptions file
* Update the kubescape binary and nsa framework json URLs and shasums
* Misc refactors
* Update examples/Makefile with a new target `make help` that will list all make targets
Fixes #72
=> Docs and refactors for better `kubescape` scanning of BB example

examples/postgres-operator/values/minio-instance.yaml
@jeff-mccoy I know you said we could push to your branch if we wanted to work on things but that sounds like a cardinal sin of git so I couldn't bring myself to do it..
After this change the postgres example comes up fully!
=> add zarf-registry PullSecret to minio-instance for Postgres example

cli/internal/packager/create.go, e2e.sh, test/e2e/e2e_gitea_and_grafana_test.go
* Write E2E test that ensures Gitea and Grafana come up cleanly
* Fix a lint error that pre-commit was picking up
=> Write E2E test for Gitea and Grafana

.gitignore, .tool-versions, Makefile, e2e.sh, test/e2e/e2e_data_injection_test.go, test/e2e/e2e_git_based_helm_chart_test.go, test/tf/public-ec2-instance/main.tf
Write the E2E tests for the data injection and single-big-bang-package examples
=> Write new E2E tests for Data Injection and Git-Based Helm Chart

README.md
Fixes #390.  Thanks @bandrea83
=> Fix README NodePort Value

.github/workflows/build-zarf-agent.yml
Create a github action for the zarf agent image to be built (this has to be merged into master before it's useful, sadly...)
=> Add Zarf Agent Github Action

README.md, docs/components.md, packages/zarf-agent/manifests/webhook.yaml, src/cmd/destroy.go, src/internal/helm/destroy.go, src/internal/helm/post-render.go, src/internal/k8s/namespace.go, src/internal/packager/seed.go
=> Zarf Agent: ignore existing namespaces on zarf init

examples/README.md
Removes the overview page from the autogenerated examples page.
None
=> Slice out the first overview page

.github/workflows/Vagrantfile, .github/workflows/build-rust-injector.yml, .github/workflows/release.yml, .github/workflows/test-k3d.yml, .github/workflows/test-k3s.yml, .github/workflows/test-kind.yml, .github/workflows/test-rhel-k3s.yml
- Add K3s red hat-based test using Rocky LInux
- Add runner labels for targeting specific envs
- Add Vagrantfile for self-hosted runners
=> add self-hosted runner code & update for multi-os test support

src/internal/api/packages/find.go, src/internal/api/packages/read.go, src/internal/api/start.go, src/ui/lib/api.ts, src/ui/lib/store.ts, src/ui/routes/initialize/+layout.svelte, src/ui/routes/initialize/deploy/+page.svelte, src/ui/routes/initialize/review/+page.svelte
=> Wip wiring up deploy UI

src/internal/git/push.go, src/internal/images/push.go, src/internal/k8s/tunnel.go
=> Poking around

examples/terraform/README.md, examples/terraform/main.tf, examples/terraform/zarf.yaml
Adds a barebones example for deploying Terraform
Fixes #856 
Documentation
=> adds barebones terraform example

docs/0-zarf-overview.md
I found some typos reviewing the Zarf docs site, specifically the [overview page](https://docs.zarf.dev/docs/zarf-overview).
Fixes # (issue)
=> Doc: Updated typos on the 0-zarf-overview.md page.

.github/workflows/scan-cves.yml
=> Run CVE check when deps change + nightly

packages/big-bang-core/kustomization/core-standard/kustomization.yaml, packages/big-bang-core/kustomization/core-standard/values.yaml, packages/big-bang-core/zarf.yaml, packages/flux-iron-bank/zarf.yaml
Update the big bang core package to `1.47.0`
N/A
```
kubectl get po,hr -A
NAMESPACE           NAME                                                            READY   STATUS      RESTARTS        AGE
kube-system         pod/coredns-b96499967-xs824                                     1/1     Running     0               68m
kube-system         pod/local-path-provisioner-7b7dc8d6f5-cbtpw                     1/1     Running     0               68m
zarf                pod/zarf-docker-registry-56fc86bd86-dmtkz                       1/1     Running     0               40m
zarf                pod/agent-hook-6c67479b95-2ql65                                 1/1     Running     0               39m
zarf                pod/agent-hook-6c67479b95-vztmb                                 1/1     Running     0 …
```
=> Update big bang core package to 1.47.0

docs/4-user-guide/4-vscode.md
Update schema validation url
Fixes #1052
=> fix: update schema validation url in docs (#1052)

.github/workflows/nightly.yml
=> Add nightly snapshot release

.github/actions/save-logs/action.yaml, .github/workflows/release.yml, .github/workflows/scan-docs-and-schema.yml, .github/workflows/test-external.yml, .github/workflows/test-k3d.yml, .github/workflows/test-k3s.yml, .github/workflows/test-kind.yml, .github/workflows/test-ui.yml
Co-authored-by: Jeff McCoy <code@jeffm.us>
This fixes the save logs function in our github actions
Fixes # N/A
N/A
=> Update save-logs in workflows to always run properly

packages/big-bang-core/kustomization/core-standard/kustomization.yaml, packages/big-bang-core/zarf.yaml, packages/flux-iron-bank/zarf.yaml
Updates the Big Bang package example to 1.48.0
```console
NAMESPACE           NAME                                                            READY   STATUS      RESTARTS   AGE
kube-system         pod/local-path-provisioner-7b7dc8d6f5-2w5xh                     1/1     Running     0          45m
kube-system         pod/coredns-b96499967-l5grj                                     1/1     Running     0          45m
kube-system         pod/metrics-server-668d979685-sktj8                             1/1     Running     0          45m
zarf                pod/zarf-docker-registry-7cbb965f59-2hrqd                       1/1     Running     0          41m
zarf                pod/agent-hook-6c67479b95-7sqs2                                 1/1     Running     0          41m
zarf …
```
=> Update Big Bang package to 1.48.0

src/cmd/tools.go, src/internal/cluster/injector.go, src/internal/cluster/seed.go, src/internal/cluster/state.go, src/internal/cluster/zarf.go, src/internal/packager/helm/chart.go, src/internal/packager/helm/destroy.go, src/internal/packager/helm/post-render.go, src/pkg/k8s/secrets.go, src/pkg/packager/deploy.go, src/pkg/packager/remove.go
This PR standardizes helm action timeouts and improves chart removal behavior.
Fixes #1063
=> Standardize timeouts for helm actions and improve remove behavior

docs/4-user-guide/1-the-zarf-cli/index.md
I went through and fixed some typos and grammar. I also updated the output of running the zarf --help command to reflect the current output.
...
Fixes #
=> Update Zarf CLI doc page

README.md
This fixes https://github.com/badges/shields/issues/8671
Fixes #N/A
=> Fix the shields badge for our release workflow

.github/actions/packages/action.yaml, Makefile
Faster local image building - should speed up CI and be smarter about when to build
Fixes #N/A
=> Hotfix test faster local build

renovate.json
This adds `go mod tidy` to renovate and permits update grouping to reduce the noise/pain of renovate updates.
=> renovate qol improvements

docs-website/docusaurus.config.js, docs-website/package-lock.json, docs-website/package.json, docs/4-user-guide/4-package-command-lifecycle.md
Add Mermaid plugin
Resolve MD Linting issues
=> Enable Mermaid diagrams

examples/component-actions/zarf.yaml, src/pkg/message/spinner.go, src/pkg/packager/actions.go, src/pkg/utils/exec/exec.go
Cleans up the code introduced in the docker-playground to work in more cases and stream logs correctly.
Fixes #N/A
=> Merge Jeff+Wayne action ideas

.github/workflows/test-minikube.yml, examples/flux-test/podinfo-source.yaml, examples/flux-test/zarf.yaml, src/injector/src/main.rs, zarf-config.toml
Fixes injector issues with the docker runtime and the oci seed image.
Fixes #N/A
=> Hotfix docker CRI support 

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/tech_debt.md
This updates our issue templates to include a tech debt kind and use headers instead of bold.
Fixes #N/A
=> Cleanup issue templates

src/cmd/internal.go, src/cmd/package.go, src/cmd/prepare.go, src/config/lang/english.go
code cleanup, using lang/english
...
Fixes #1341
=> update internal, package, prepare to use lang/english

.github/pull_request_template.md
Update our pr template to include a relates to issue #.
Fixes #n/a
=> Add relates to to our pr template for multi-pr issues

.github/workflows/scorecard.yaml, README.md
A new workflow created which will track the  pushed changes and automatically check for the  vulnerabilities with the help of CodeQL in the repo every week.
...
Fixes #897 
Relates to #
=> Openssf rating and github action file for the same

docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
Found 2 more bad links. 
The project looks nice, added it to the list of potential useful tools :) 
No related Issue
=> chore(docs): Fix links in zarf-packages docs

CONTRIBUTING.md
Fixes an inaccurate directory reference in the contributing guide.
=> Fix directory reference for ADRs

src/pkg/packager/publish.go, src/pkg/packager/pull.go, src/pkg/utils/oras.go, src/test/e2e/50_oci_package_test.go
=> 1445 bugs in package pull and package publish

.github/workflows/test-bigbang.yml
This is a better way to skip our BB tests
Fixes #N/A
=> A better way to skip the BB test

docs/3-getting-started.md
Documentation does not reflect the editorial guidelines outlined in the Project Style Guide. Editing the "Getting Started" page to align with the updated Style Guide to improve readability for users.
- Removing excess '!'
- Adding more context to the Getting Started overview
- Adding punctuation to list
- Editing some context to improve readability
- Correcting heading capitalization
- Fixing link text at the bottom of the page
Fixes #1498
=> Docs edits to "Getting Started" page

.github/workflows/release.yml
Removes built test packages after testing and prior to release.
Fixes N/A
=> Hotfix the release running out of space

docs/4-user-guide/2-zarf-packages/index.md
Documentation does not reflect the editorial guidelines outlined in the Project Style Guide. Editing the "Zarf Packages" page to align with the updated Style Guide to improve readability for users.
- Remove the admonition note at the bottom of the page and convert it to list formatting
- Improve language used to describe packages to improve readability
- Improve the tone of writing to align with style guide
- Capitalize K8s
Fixes #1536
=> Docs edits for "Zarf Packages" page

examples/big-bang/zarf.yaml
=> Bump BB Version

src/pkg/utils/io.go, src/types/component.go, src/types/extensions/README.md, src/types/runtime.go
This resolves linting issues from the last release
Fixes N/A
=> Resolve linting issues from last release

examples/big-bang/zarf.yaml
This bumps up to 1.57.1 version of Big Bang on the example.
N/A
=> Bump to Big Bang 1.57.1

.github/workflows/release.yml
This updates the permissions for github.token / GITHUB_TOKEN to be more explicit.
Fixes #N/A
=> Update release workflow permissions to be more explicit

src/pkg/packager/common.go
This hotfix was requested to improve the UX around package signing.
Fixes #N/A
=> Make key not provided msg friendlier

docs/6-developer-guide/2-testing.md
Documentation does not reflect the editorial guidelines outlined in the Project Style Guide. Editing the "Code Testing" page to align with the updated Style Guide to improve readability for users.
- Adding punctuation to lists
- Improving professional language
- Changing title/editing capitalization
Fixes #1604
=> Docs edits to "Code Testing" page

.github/workflows/release.yml, .goreleaser.yaml, README.md, hack/print-ui-diff.sh, src/internal/packager/images/pull.go, src/pkg/message/message.go, src/pkg/packager/deprecated/common.go, src/pkg/transform/image.go
This cleans up the UI diff check script for local dev and a few linting issues.
Fixes #1614
=> Fix linting and UI version check

src/extensions/bigbang/bigbang.go, src/extensions/bigbang/manifests.go, src/extensions/bigbang/test/bigbang_test.go, src/extensions/bigbang/test/package/disable-all-bb1.yaml, src/extensions/bigbang/test/package/disable-all-bb2.yaml, src/extensions/bigbang/test/package/zarf.yaml
This improves BB 2.0 support and fixes upgrades.
Fixes #N/A
=> Fix the Big Bang tests to support upgrading v1 to v2

.github/workflows/auto-assign-to-project.yml, .github/workflows/build-rust-injector.yml, .github/workflows/release.yml, .github/workflows/scan-codeql.yml, .github/workflows/scan-cves.yml, .github/workflows/scan-docs-and-schema.yml, .github/workflows/scan-labels.yml, .github/workflows/scan-lint.yml, .github/workflows/test-bigbang.yml, .github/workflows/test-external.yml, .github/workflows/test-k3d.yml, .github/workflows/test-k3s.yml, .github/workflows/test-kind.yml, .github/workflows/test-minikube.yml, .github/workflows/test-ui.yml, .github/workflows/test-unit.yml, .github/workflows/test-upgrade.yml, .github/workflows/test-windows.yml
This adds specific token permissions to each workflow.
Fixes #N/A
=> Add explicit permissions to each workflow

.github/workflows/release.yml
Reference the build dir instead of the PATH in the clear cache step
Fixes #N/A
- [N/A] Test, docs, adr added or updated as needed
=> Fix the release.yml workflow

.github/workflows/release.yml
Reduce release space even further.
Fixes #N/A
- [N/A] Test, docs, adr added or updated as needed
=> Make release process cleanup more aggressive

packages/zarf-agent/zarf.yaml, src/pkg/packager/compose.go, src/test/test-packages/51-import-everything/bar/zarf.yaml
This adds action directory composability to the OCI PR
Fixes N/A
=> Compose action dirs relative to the child

src/internal/packager/git/clone.go
This passes auth (if specified) to the `git` fetch that is called on full repo clones.
Fixes #N/A
=> Hotfix full-repo authenticated git clone

.github/workflows/release.yml, src/test/e2e/50_oci_package_test.go, src/test/e2e/52_oci_compose_differential_test.go
This fixes issues with releases running out of space.
Fixes #N/A
=> Fix some issues with releases running out of space

src/ui/routes/packages/[name]/deploy/+page.svelte
Fixed the error handling in the deploy page to account for fatal errors and to ensure the finalized state reflects the failed components. 
Fixes #
#1582
=> Fixed deploy page fatal and response error handling. 

.github/workflows/release.yml
This fixes the `needs` statement on the release workflow.
Fixes #N/A
=> Fix release workflow needs statement

CODEOWNERS
This updates our CODEOWNERS to replace @YrrepNoj with @cmwylie19 
Fixes #N/A
=> Update CODEOWNERS to replace Jon with Case

docs/0-zarf-overview.md
The overview file used a mix of syntax for admonitions. I simplified it to prepare for conversion.
=> Use standard admonition syntax

.github/actions/slack/action.yaml
This fixes our slack notification on nightly failures.
Fixes #N/A
=> Add a text section to the slack json

src/test/e2e/22_git_and_flux_test.go
This adds the new prune command to the flux test as well to reduce disk pressure.
Fixes #N/A
=> Add a prune statement to the flux repository test

src/extensions/bigbang/test/package/disable-all-bb2.yaml
This PR fixes the BB tests due to changes in BB defaults.
Fixes #N/A
=> Remove grafana from the values file for BB tests

.github/workflows/release.yml
This hotfixes the release workflow to remove files to reduce disk pressure on releases.
Fixes #N/A
=> Cleanup files in release workflow

src/pkg/oci/pull.go
=> fix: use Docker's transform to ensure image refs are consistency parsed

docs/1-getting-started/0-understand-the-basics.md
=> docs: update airgap software delivery course name

.github/workflows/test-bigbang.yml
Update references to new ironbank credentials in bigbang workflow
N/A
=> chore: update references to new ironbank credentials in bigbang workflow

.github/workflows/release.yml
Update the release workflow for the sigstore update.
Fixes #N/A
=> chore: update the release workflow to accept sigstore terms and sign by digest

.github/workflows/release.yml
Small fix for signing in the release workflow
Fixes #N/A
=> chore: update sha to @ syntax instead of :

README.md
Just a small spelling error when I was reading how you are handling your `community` stuff around slack.
Fixes #
Relates to #
=> chore: small spell error

src/extensions/README.md
=> docs: fix typos in extension readme

renovate.json
This adds a second check for inverted versions/urls in chart definitions
Fixes #N/A
=> chore: update renovate.json to catch inverse charts

CODEOWNERS
This adds @AustinAbro321 as a CODEOWNER to review PRs
Fixes #N/A
=> chore: update CODEOWNERS with @AustinAbro321

.github/workflows/release.yml
=> chore(release): update release workflow to use token from gh app

examples/longhorn/zarf.yaml, src/pkg/packager/creator/normal.go
allow absolute paths for differential packages
fixes: #2396
=> fix: allow absolute paths for differential packages

netlify.toml, site/astro.config.ts
add redirect for examples
https://docs.zarf.dev/examples/
=> docs: add redirect for examples

site/src/components/SchemaItemProperties.astro
site has broken schema integration
=> fix: schema integration

README.md
Fix from last PR
Fixes #
Relates to #
=> docs: fix casing on code of conduct badge

CODEOWNERS
Adding @dgershman (from @radiusmethod) as a CODEOWNERS.
N/A
=> chore: adding @dgershman

.golangci.yaml, src/extensions/bigbang/bigbang_test.go, src/pkg/packager/lint/lint_test.go, src/test/e2e/00_use_cli_test.go, src/test/e2e/05_tarball_test.go, src/test/e2e/21_connect_creds_test.go, src/test/e2e/51_oci_compose_test.go, src/test/external/ext_out_cluster_test.go
Adds testifylint and fixes any issues related to it.
Part of #2503 
Depends on #2499
=> refactor: enable testifylint linter

.grype.yaml
#2457 removed rouille as a dependency
=> chore: remove rouille CVE from grype ignore

src/pkg/packager/creator/compose_test.go
=> test: creator.ComposeComponents

src/types/package.go, zarf.schema.json
This was a field reserved for the, now deprecated, Zarf UI
=> feat: remove .metadata.image from schema

Makefile
Many actions in the make file don't need every cli, just the regular build is enough
=> chore: make less

src/pkg/packager/creator/creator_test.go, src/pkg/packager/creator/normal_test.go
=> test: move creator tests into one file

.github/workflows/test-site.yml, site/hack/copy-examples.js, site/linkinator.config.json, site/package-lock.json
=> test: site and links

.github/workflows/test-unit.yml
=> chore: run unit tests on main

.github/workflows/compare-cves.yml, .github/workflows/dependency-review.yml, .github/workflows/scan-codeql.yml, .github/workflows/scan-docs-and-schema.yml, .github/workflows/scan-lint.yml, .github/workflows/test-bigbang.yml, .github/workflows/test-e2e-shim.yml, .github/workflows/test-e2e.yml, .github/workflows/test-external.yml, .github/workflows/test-site.yml, .github/workflows/test-unit.yml, .github/workflows/test-upgrade.yml, .github/workflows/test-windows.yml
This adds merge groups to tests so that we can start using them
=> ci: add merge groups

.pre-commit-config.yaml, src/test/common.go, src/test/e2e/20_zarf_init_test.go, src/test/e2e/21_connect_creds_test.go, src/test/e2e/22_git_and_gitops_test.go, src/test/e2e/23_data_injection_test.go, src/test/e2e/24_variables_test.go, src/test/e2e/25_helm_test.go, src/test/e2e/26_simple_packages_test.go, src/test/e2e/27_deploy_regression_test.go, src/test/e2e/28_wait_test.go, src/test/e2e/29_config_file_test.go, src/test/e2e/30_component_action_cluster_test.go, src/test/e2e/31_checksum_and_signature_test.go, src/test/e2e/32_component_webhooks_test.go, src/test/e2e/34_custom_init_package_test.go, src/test/e2e/35_custom_retries_test.go, src/test/e2e/50_oci_publish_deploy_test.go, src/test/e2e/51_oci_compose_test.go, src/test/e2e/99_appliance_remove_test.go, src/test/e2e/99_yolo_test.go, src/test/e2e/main_test.go, src/test/nightly/ecr_publish_test.go
This eliminates the possibility of skipping tests in e2e tests.
=> test: simplifying e2e test checks

CODEOWNERS
=> docs: fix codeowners file

.github/workflows/nightly-eks.yml, examples/kiwix/manifests/deployment.yaml, packages/distros/eks/eks.yaml, packages/distros/eks/zarf.yaml
Still some breakages in the eks test
=> ci: improve nightly eks test

.golangci.yaml, src/extensions/bigbang/test/bigbang_test.go, src/pkg/cluster/injector_test.go, src/test/e2e/22_git_and_gitops_test.go
This change enabling checking for unchecked type assertions and fixes any current violation that we have.
N/A
=> fix: type assertion error checking and enforce linter

src/cmd/destroy.go, src/cmd/internal.go, src/cmd/tools/crane.go, src/config/lang/english.go, src/internal/agent/hooks/argocd-application.go, src/internal/agent/hooks/argocd-repository.go, src/internal/agent/hooks/flux-gitrepo.go, src/internal/agent/hooks/flux-helmrepo.go, src/internal/agent/hooks/flux-ocirepo.go, src/internal/agent/hooks/pods.go, src/pkg/cluster/state.go, src/pkg/packager/deploy.go
This change refactors places where we are ignoring the load Zarf state error or just logging it instead of returning.
=> refactor: load state to return error if loading fails

.github/workflows/release.yml
=> fix: zarf dev instead of zerf-dev

.github/dependabot.yaml, renovate.json
This moves us away from renovate to dependabot where possible
=> fix: add dependabot and disable renovate features

site/src/content/docs/ref/deploy.mdx
=> docs: explain no wait & helm hooks interaction

.github/workflows/scan-lint.yml, .golangci.yaml
We are getting flakes from lint timing out
=> ci: increase lint timeout

.github/workflows/release.yml
=> ci: permission at job level

site/src/content/docs/ref/deploy.mdx, site/src/content/docs/tutorials/3-deploy-a-retro-arcade.mdx
Correct docs to use updated reference to dos-games 1.1.0 package. 
Fixes #3003
- [ X ] Test, docs, adr added or updated as needed
- [ X ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed
=> docs: update dos-games refs

site/src/content/docs/getting-started/interactive-tutorial.mdx
Adding instruqt tutorial to docs site
=> docs: add instruqt interactive tutorial

src/test/packages/25-evil-dos-games/zarf.yaml
We moved away from dockerhub for most of our images to avoid TOOMANYREQUEST flakes in actions, but forgot about this one
=> chore: dos-games dockerhub image to ghcr

go.mod
This change updates Go to 1.23.3.
N/A
=> Update Go to 1.23.3

src/internal/packager2/layout/create.go, src/internal/packager2/layout/create_test.go
Validate that the submitted flavor exists
Fixes #2587
=> feat: validate submitted flavor exists

.github/workflows/build-rust-injector.yml
Update init s3 publish path
This was something I forgot to do in #3380
=> chore: update init s3 publish path

.github/workflows/build-rust-injector.yml, packages/zarf-registry/zarf.yaml, zarf-config.toml
Follow up to #3600. now that the new injector is published, this updates the init package to use it.
=> chore: update init package injector

examples/composable-packages/zarf.yaml, site/src/content/docs/getting-started/index.mdx, site/src/content/docs/ref/deploy.mdx, src/pkg/lint/lint_test.go, src/pkg/lint/testdata/lint-with-imports/linted-import/zarf.yaml, src/test/e2e/09_component_compose_test.go, src/test/e2e/11_oci_pull_inspect_test.go, src/test/e2e/27_deploy_regression_test.go
Published a new package signed with the new key here - https://github.com/zarf-dev/zarf/actions/runs/14089306390
This updates the code to use that new package
=> chore: update dos-games references to use new version

README.md, site/src/content/docs/commands/zarf.md, site/src/content/docs/commands/zarf_tools_helm.md, site/src/content/docs/contribute/nerd-notes.mdx, site/src/content/docs/getting-started/understanding.mdx, site/src/content/docs/ref/actions.mdx, site/src/content/docs/ref/components.mdx, site/src/content/docs/ref/sboms.mdx, site/src/content/docs/tutorials/0-creating-a-zarf-package.mdx, site/src/content/docs/tutorials/2-deploying-zarf-packages.mdx, site/src/content/docs/tutorials/7-custom-init-packages.mdx, src/config/lang/english.go, src/pkg/packager/mirror.go
See #3635 for scope of work. In the future we should also update Homebrew via .goreleaser.yaml.
Fixes #3635
=> docs: Migrate "air gap" to "airgap"

.goreleaser.yaml
Updates the brew description for Zarf. On next release, the screenshot below should reflect "Airgap."
Followup to #3638
=> chore: update Zarf Homebrew description

packages/distros/k3s/zarf.yaml, src/test/e2e/20_zarf_init_test.go
Routine update to the k3s version.
=> chore(deps): update k3s version

src/cmd/dev.go, src/internal/packager2/generate.go
=> refactor: generate

src/internal/packager/images/common.go, src/internal/packager/images/pull.go, src/internal/packager/images/push.go, src/pkg/cluster/tunnel.go
Restore some retry logic changed in #3559 
Relates to #2104 , #1568 , #1218
=> fix: retry on images and components

src/pkg/utils/network.go
respect context during HTTP file downloads
fixes #2647
=> feat: respect context during HTTP file downloads

src/cmd/dev_test.go, src/cmd/package_test.go, src/cmd/testdata/inspect-manifests/chart/chart/templates/deployment.yaml, src/cmd/testdata/inspect-manifests/chart/values.yaml, src/cmd/testdata/inspect-manifests/chart/zarf.yaml, src/cmd/testdata/inspect-values-files/chart/chart/templates/deployment.yaml, src/cmd/testdata/inspect-values-files/chart/expected.yaml, src/cmd/testdata/inspect-values-files/chart/values.yaml, src/internal/packager2/inspect.go, zarf.yaml
Fixes a bug `zarf package inspect values-files` does not template the value templates
=> fix: template variables in values file in `zarf package inspect value-files`

src/pkg/zoci/common.go
`zarf package pull` recently started caching layers as of #3767. The `config.CommonOptions.CachePath` is always set during CLI pulls, however since we are not setting the cachepath in several unit tests, running unit tests on main creates several folders in the users local directory. 
This does allow users to run `zarf package pull --zarf-cache=""` to avoid caching the package entirely, and they can run `zarf package pull --zarf-cache="."` to cache in the current directory. 
This relates to #3774 as Zarf should have more intuitive options to allow users to cache or not cache. Prioritizing this as tests are messy on main currently.
=> feat: avoid using a cache in `zarf package pull` is cachepath is not set

RELEASES.md
Documents the release process as an initial structure to build upon. Adds more granular review steps for Release Candidate review.
Relates to #3766
=> chore(sustainability): document the release process

site/src/content/docs/tutorials/0-creating-a-zarf-package.mdx
...
Fixes #
Relates to #
- [ x] Test, docs, adr added or updated as needed
- [x ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed
=> docs: Update 0-creating-a-zarf-package.mdx

packages/zarf-agent/manifests/webhook.yaml, src/internal/agent/hooks/argocd-appproject.go, src/internal/agent/hooks/argocd-appproject_test.go, src/internal/agent/start.go
The PR adds a webhook which patches the SourceRepos in argocd AppProjects
Fixes #3952
- [x ] Test, docs, adr added or updated as needed
=> add webhook for argocd appprojects

netlify.toml
Netlify sites have been failing deploy on the ignore check. See these Deploy logs from July 16th. https://app.netlify.com/projects/zarf-docs/deploys/6877c9b2d423a20008567776. 
This removes the ignore check and deploys the site every time for simplicity.
=> chore: remove netlify ignore
